var firstNames = {
    "Martina": "F",
    "Emma": "F",
    "Jana": "F",
    "Lucia": "F",
    "Iker": "M",
    "Leo": "M",
    "Martí": "M",
    "Biel": "M",
    "Dylan": "M",
    "Jordi": "M",
    "Marc": "M",
    "Maryam": "F",
    "Fatima": "F",
    "Lyn": "F",
    "Hur": "F",
    "Lian": "F",
    "Maria": "F",
    "Malak": "F",
    "Nur": "F",
    "Mila": "F",
    "Farah": "F",
    "Mohamed": "M",
    "Abdullah": "M",
    "Ahmed": "M",
    "Ali": "M",
    "Yousouf": "M",
    "Omar": "M",
    "Adam": "M",
    "Abd": "M",
    "Khaled": "M",
    "Fahd": "M",
    "Amelia": "F",
    "Ajla": "F",
    "Aria": "F",
    "Amelja": "F",
    "Leandra": "F",
    "Ambra": "F",
    "Klea": "F",
    "Melisa": "F",
    "Amaris": "F",
    "Reina": "F",
    "Noel": "M",
    "Aron": "M",
    "Joel": "M",
    "Roan": "M",
    "Amar": "M",
    "Mateo": "M",
    "Alteo": "M",
    "Roel": "M",
    "Luis": "M",
    "Dion": "M",
    "Anahit": "F",
    "Gayane": "F",
    "Anna": "F",
    "Karine": "F",
    "Hasmik": "F",
    "Lusine": "F",
    "Susanna": "F",
    "Armine": "F",
    "Narine": "F",
    "Lilit": "F",
    "Armen": "M",
    "Artur": "M",
    "Karen": "M",
    "Samvel": "M",
    "Gevorg": "M",
    "Ashot": "M",
    "Davit": "M",
    "Arman": "M",
    "Hovhannes": "M",
    "Gagik": "M",
    "Nare": "F",
    "Arpi": "F",
    "Maneh": "F",
    "Angelina": "F",
    "Mari": "F",
    "Eva": "F",
    "Mariam": "F",
    "Sofi": "F",
    "Narek": "M",
    "Monte": "M",
    "Tigran": "M",
    "Areg": "M",
    "Hayk": "M",
    "Mark": "M",
    "Mikayel": "M",
    "Aleks": "M",
    "Areni": "M",
    "Olivia": "F",
    "Isabella": "F",
    "Alma": "F",
    "Catalina": "F",
    "Mia": "F",
    "Ámbar": "F",
    "Victoria": "F",
    "Delfina": "F",
    "Bautista": "M",
    "Juan": "M",
    "Felipe": "M",
    "Bruno": "M",
    "Noah": "M",
    "Benicio": "M",
    "Thiago": "M",
    "Ciro": "M",
    "Liam": "M",
    "Marie": "F",
    "Emilia": "F",
    "Lena": "F",
    "Laura": "F",
    "Valentina": "F",
    "Hannah": "F",
    "Lea": "F",
    "Paul": "M",
    "Jakob": "M",
    "Maximilian": "M",
    "Elias": "M",
    "David": "M",
    "Felix": "M",
    "Leon": "M",
    "Tobias": "M",
    "Jonas": "M",
    "Sophia": "F",
    "Sara": "F",
    "Sophie": "F",
    "Elena": "F",
    "Luka": "M",
    "Theodor": "M",
    "Mohammad": "M",
    "Alexander": "M",
    "Charlotte": "F",
    "Isla": "F",
    "Ava": "F",
    "Matilda": "F",
    "Ella": "F",
    "Grace": "F",
    "Willow": "F",
    "Oliver": "M",
    "William": "M",
    "Henry": "M",
    "Jack": "M",
    "Theodore": "M",
    "Hudson": "M",
    "Charlie": "M",
    "Luca": "M",
    "Alysha": "F",
    "Isabelle": "F",
    "Emily": "F",
    "Emely": "F",
    "Daniel": "M",
    "Dyllan": "M",
    "Kevin": "M",
    "Keven": "M",
    "Elchin": "M",
    "Vugar": "M",
    "Anar": "M",
    "Elnur": "M",
    "Samir": "M",
    "Elshan": "M",
    "Rashad": "M",
    "Ilgar": "M",
    "Vusal": "M",
    "Zahra": "F",
    "Aylin": "F",
    "Zeynab": "F",
    "Nilay": "F",
    "Ayla": "F",
    "İnci": "F",
    "Nuray": "F",
    "Huseyn": "M",
    "Yusif": "M",
    "Mahammad": "M",
    "Raul": "M",
    "Murad": "M",
    "Tunar": "M",
    "Sevinj": "F",
    "Gunel": "F",
    "Leyla": "F",
    "Aygun": "F",
    "Gunay": "F",
    "Sevda": "F",
    "Vusala": "F",
    "Konul": "F",
    "Aysel": "F",
    "Tarana": "F",
    "Merjem": "F",
    "Asja": "F",
    "Esma": "F",
    "Amina": "F",
    "Ema": "F",
    "Hana": "F",
    "Lejla": "F",
    "Lamija": "F",
    "Dalila": "F",
    "Davud": "M",
    "Hamza": "M",
    "Adin": "M",
    "Džan": "M",
    "Daris": "M",
    "Eman": "M",
    "Harun": "M",
    "Mohammed": "M",
    "Abdul": "M",
    "Muhammad": "M",
    "Syed": "M",
    "Kazi": "M",
    "Sheikh": "M",
    "Hasan": "M",
    "Louise": "F",
    "Alice": "F",
    "Camille": "F",
    "Lina": "F",
    "Sofia": "F",
    "Juliette": "F",
    "Arthur": "M",
    "Louis": "M",
    "Jules": "M",
    "Lucas": "M",
    "Gabriel": "M",
    "Victor": "M",
    "Oscar": "M",
    "Martha": "F",
    "Roxana": "F",
    "Ana Maria": "F",
    "Elizabeth": "F",
    "Sonia": "F",
    "Juana": "F",
    "Patricia": "F",
    "Lidia": "F",
    "Rosmery": "F",
    "Carmen": "F",
    "Juan Carlos": "M",
    "José Luis": "M",
    "Marco Antonio": "M",
    "Miguel Ángel": "M",
    "Mario": "M",
    "Ferndo": "M",
    "Victor Hugo": "M",
    "Jorge": "M",
    "Ana": "F",
    "Francisca": "F",
    "Antônia": "F",
    "Adriana": "F",
    "Juliana": "F",
    "Marcia": "F",
    "Fernanda": "F",
    "Patrícia": "F",
    "Aline": "F",
    "José": "M",
    "João": "M",
    "Antônio": "M",
    "Francisco": "M",
    "Carlos": "M",
    "Paulo": "M",
    "Pedro": "M",
    "Luiz": "M",
    "Marcos": "M",
    "Helena": "F",
    "Maria Alice": "F",
    "Manuela": "F",
    "Maitê": "F",
    "Liz": "F",
    "Cecília": "F",
    "Miguel": "M",
    "Gael": "M",
    "Théo": "M",
    "Heitor": "M",
    "Ravi": "M",
    "Davi": "M",
    "Berrdo": "M",
    "Alisa": "F",
    "Hanna": "F",
    "Maryja": "F",
    "Safija": "F",
    "Maksim": "M",
    "Michail": "M",
    "Chloe": "F",
    "Benjamin": "M",
    "Thomas": "M",
    "Logan": "M",
    "Florence": "F",
    "Léa": "F",
    "Livia": "F",
    "Rose": "F",
    "Édouard": "M",
    "Jacob": "M",
    "Nathan": "M",
    "Nora": "F",
    "Alina": "F",
    "Matteo": "M",
    "Lio": "M",
    "Nino": "F",
    "Sofía": "F",
    "Julieta": "F",
    "Trinidad": "F",
    "Isidora": "F",
    "Agustina": "F",
    "Josefa": "F",
    "Gaspar": "M",
    "Santiago": "M",
    "Benjamín": "M",
    "Agustín": "M",
    "Vicente": "M",
    "Maximiliano": "M",
    "Tomás": "M",
    "Antonella": "F",
    "Luciana": "F",
    "Celeste": "F",
    "Gabriela": "F",
    "Mariana": "F",
    "Salomé": "F",
    "Guadalupe": "F",
    "Matías": "M",
    "Jerónimo": "M",
    "Gerónimo": "M",
    "Emiliano": "M",
    "Martín": "M",
    "Samuel": "M",
    "Emmanuel": "M",
    "Isaac": "M",
    "Eliška": "F",
    "Adéla": "F",
    "Tereza": "F",
    "Sofie": "F",
    "Viktorie": "F",
    "Karolína": "F",
    "Natálie": "F",
    "Amálie": "F",
    "Julie": "F",
    "Jakub": "M",
    "Jan": "M",
    "Tomáš": "M",
    "Matyáš": "M",
    "Filip": "M",
    "Vojtěch": "M",
    "Lukáš": "M",
    "Martin": "M",
    "Matěj": "M",
    "Leni": "F",
    "Clara": "F",
    "Finn": "M",
    "Theo": "M",
    "Emil": "M",
    "Ben": "M",
    "Ida": "F",
    "Freja": "F",
    "Luna": "F",
    "Agnes": "F",
    "Asta": "F",
    "Frida": "F",
    "Alberte": "F",
    "Carl": "M",
    "Malthe": "M",
    "Valdemar": "M",
    "Aksel": "M",
    "August": "M",
    "Abdelkader": "M",
    "Rachid": "M",
    "Said": "M",
    "Brahim": "M",
    "Djamel": "M",
    "Imene": "F",
    "Yasmine": "F",
    "Lyna": "F",
    "Meriem": "F",
    "Karima": "F",
    "Melissa": "F",
    "Lydia": "F",
    "Mía": "F",
    "Danna": "F",
    "María": "F",
    "Lía": "F",
    "Aitana": "F",
    "Ian": "M",
    "Ángel": "M",
    "Lenna": "F",
    "Marta": "F",
    "Elli": "F",
    "Sandra": "F",
    "Oskar": "M",
    "Sebastian": "M",
    "Hugo": "M",
    "Robin": "M",
    "Lukas": "M",
    "Rasmus": "M",
    "Mary": "F",
    "Marina": "F",
    "Irene": "F",
    "Habiba": "F",
    "Marwa": "F",
    "Nada": "F",
    "Salma": "F",
    "Peter": "M",
    "Pierre": "M",
    "George": "M",
    "John": "M",
    "Mina": "M",
    "Beshoi": "M",
    "Kirollos": "M",
    "Fadi": "M",
    "Habib": "M",
    "Shaimaa": "F",
    "Fatma": "F",
    "Maha": "F",
    "Reem": "F",
    "Farida": "F",
    "Aya": "F",
    "Shahd": "F",
    "Ashraqat": "F",
    "Sahar": "F",
    "Fatin": "F",
    "Dalal": "F",
    "Doha": "F",
    "Fajr": "F",
    "Suha": "F",
    "Rowan": "F",
    "Hosniya": "F",
    "Hasnaa": "F",
    "Hosna": "F",
    "Gamila": "F",
    "Gamalat": "F",
    "Youssef": "M",
    "Mahmoud": "M",
    "Mustafa": "M",
    "Yassin": "M",
    "Taha": "M",
    "Bilal": "M",
    "Ibrahim": "M",
    "Hassan": "M",
    "Hussein": "M",
    "Karim": "M",
    "Tareq": "M",
    "Abdel-Rahman": "M",
    "Halim": "M",
    "Selim": "M",
    "Abdallah": "M",
    "Ane": "F",
    "Laia": "F",
    "June": "F",
    "Nahia": "F",
    "Maddi": "F",
    "Malen": "F",
    "Irati": "F",
    "Izaro": "F",
    "Markel": "M",
    "Julen": "M",
    "Oihan": "M",
    "Jon": "M",
    "Aiur": "M",
    "Aimar": "M",
    "Ibai": "M",
    "Danel": "M",
    "Júlia": "F",
    "Lucía": "F",
    "Ona": "F",
    "Paula": "F",
    "Nil": "M",
    "Pol": "M",
    "Pau": "M",
    "Àlex": "M",
    "Marti": "M",
    "Valeria": "F",
    "Julia": "F",
    "Daniela": "F",
    "Carla": "F",
    "Manuel": "M",
    "Alejandro": "M",
    "Pablo": "M",
    "Álvaro": "M",
    "Aino": "F",
    "Aada": "F",
    "Lilja": "F",
    "Eevi": "F",
    "Helmi": "F",
    "Venla": "F",
    "Ellen": "F",
    "Väinö": "M",
    "Eino": "M",
    "Onni": "M",
    "Eeli": "M",
    "Toivo": "M",
    "Leevi": "M",
    "Lív": "F",
    "Ria": "F",
    "Sólja": "F",
    "Hjørdis": "F",
    "Ronja": "F",
    "Vár": "F",
    "Jónas": "M",
    "Nóa": "M",
    "Andrias": "M",
    "Jógvan": "M",
    "Markus": "M",
    "Mattias": "M",
    "Adrian": "M",
    "Gilli": "M",
    "Jákup": "M",
    "Tróndur": "M",
    "Jade": "F",
    "Ambre": "F",
    "Chloé": "F",
    "Léo": "M",
    "Raphaël": "M",
    "Maël": "M",
    "Tiago": "M",
    "Ivy": "F",
    "Lily": "F",
    "Freya": "F",
    "Harry": "M",
    "Rosie": "F",
    "Evie": "F",
    "Archie": "M",
    "Fiadh": "F",
    "Aoife": "F",
    "Annie": "F",
    "James": "M",
    "Oisin": "M",
    "Cillian": "M",
    "Millie": "F",
    "Harris": "M",
    "Rory": "M",
    "Alfie": "M",
    "Finlay": "M",
    "Lewis": "M",
    "Imogen": "F",
    "Penelope": "F",
    "Max": "M",
    "Maya": "F",
    "Kai": "M",
    "Ivaana": "F",
    "Nivi": "F",
    "Uiloq": "F",
    "Niviaq": "F",
    "Ivalu": "F",
    "Pipaluk": "F",
    "Malu": "F",
    "Paninnguaq": "F",
    "Aviana": "F",
    "Paneeraq": "F",
    "Inuk": "M",
    "Malik": "M",
    "Minik": "M",
    "Inunnguag": "M",
    "Ulloriaq": "M",
    "Norsaq": "M",
    "Aputsiaq": "M",
    "Ivik": "M",
    "Miki": "M",
    "Maligiaq": "M",
    "Qillaq": "M",
    "Inutsiaq": "M",
    "Nuka": "M",
    "Salik": "M",
    "María del Carmen": "F",
    "Isabel": "F",
    "María Teresa": "F",
    "Esperanza": "F",
    "Milagrosa": "F",
    "Antonio": "M",
    "Lucija": "F",
    "Nika": "F",
    "Rita": "F",
    "Dora": "F",
    "Jakov": "M",
    "Ivan": "M",
    "Roko": "M",
    "Petar": "M",
    "Niko": "M",
    "Matej": "M",
    "Fran": "M",
    "Josip": "M",
    "Widelene": "F",
    "Mirlande": "F",
    "Myrlande": "F",
    "Islande": "F",
    "Lovelie": "F",
    "Lovely": "F",
    "Judeline": "F",
    "Angeline": "F",
    "Esther": "F",
    "Chedeline": "F",
    "Jessica": "F",
    "Rose-Merline": "F",
    "Stevenson": "M",
    "Stanley": "M",
    "Peterson": "M",
    "Wilson": "M",
    "Jameson": "M",
    "Evens": "M",
    "Ricardo": "M",
    "Zoé": "F",
    "Léna": "F",
    "Boglárka": "F",
    "Lili": "F",
    "Lilien": "F",
    "Lara": "F",
    "Levente": "M",
    "Máté": "M",
    "Dominik": "M",
    "Bence": "M",
    "Olivér": "M",
    "Marcell": "M",
    "Dániel": "M",
    "Zalán": "M",
    "Ádám": "M",
    "Éabha": "F",
    "Ellie": "F",
    "Rían": "M",
    "Oisín": "M",
    "Tadhg": "M",
    "Charbel": "M",
    "Jude": "M",
    "Niel": "M",
    "Lin": "F",
    "Sama": "F",
    "Celine": "F",
    "Leah": "F",
    "Taim": "M",
    "Amir": "M",
    "Ayalah": "F",
    "Lur": "F",
    "Yasmin": "F",
    "Ahmad": "M",
    "Yusef": "M",
    "Omer": "M",
    "Shams": "F",
    "Malek": "F",
    "Jori": "F",
    "Marya": "F",
    "Ariel": "M",
    "Lavi": "M",
    "Uri": "M",
    "Refael": "M",
    "Noam": "M",
    "Eitan": "M",
    "Ari": "M",
    "Yehuda": "M",
    "Avigail": "F",
    "Tamar": "F",
    "Noa": "F",
    "Sarah": "F",
    "Adele": "F",
    "Lia": "F",
    "Ayala": "F",
    "Lillie": "F",
    "Lilly": "F",
    "Emelia": "F",
    "Emiliya": "F",
    "Edward": "M",
    "Aditi": "F",
    "Inaya": "F",
    "Aarya": "F",
    "Kiara": "F",
    "Aadhya": "F",
    "Vamika": "F",
    "Pari": "F",
    "Jiya": "F",
    "Mehar": "F",
    "Amayra": "F",
    "Shivansh": "M",
    "Dhruv": "M",
    "Kabir": "M",
    "Vedant": "M",
    "Kiaan": "M",
    "Aarav": "M",
    "Arjun": "M",
    "Viraj": "M",
    "Krishna": "M",
    "Muhammed": "M",
    "Hydar": "M",
    "Kathem": "M",
    "Ammar": "M",
    "Fatemeh": "F",
    "Helma": "F",
    "Zeinab": "F",
    "Yasna": "F",
    "Mersana": "F",
    "Nazanin-Zahra": "F",
    "Baran": "F",
    "Fatemeh-Zahra": "F",
    "Amir-Ali": "M",
    "Amir-Hossein": "M",
    "Hossein": "M",
    "AbulFazl": "M",
    "Amir-Abbas": "M",
    "Samyar": "M",
    "Mohammad-Taha": "M",
    "Ma'soumeh": "F",
    "Sakineh": "F",
    "Roghayyeh": "F",
    "Khadije": "F",
    "Somayyeh": "F",
    "Mahdi": "M",
    "Reza": "M",
    "Mohammad-Reza": "M",
    "Abbas": "M",
    "Ali-Reza": "M",
    "Embla": "F",
    "Emilía": "F",
    "Sóley": "F",
    "Aþena": "F",
    "Matthildur": "F",
    "Katla": "F",
    "Guðrún": "F",
    "Saga": "F",
    "Viktoría": "F",
    "Jökull": "M",
    "Kári": "M",
    "Jón": "M",
    "Óliver": "M",
    "Matthías": "M",
    "Mikael": "M",
    "Atlas": "M",
    "Elmar": "M",
    "Aurora": "F",
    "Giulia": "F",
    "Ginevra": "F",
    "Beatrice": "F",
    "Vittoria": "F",
    "Ludovica": "F",
    "Matilde": "F",
    "Leonardo": "M",
    "Alessandro": "M",
    "Tommaso": "M",
    "Francesco": "M",
    "Lorenzo": "M",
    "Edoardo": "M",
    "Mattia": "M",
    "Riccardo": "M",
    "Gabriele": "M",
    "Andrea": "F",
    "Sienna": "F",
    "Daisy": "F",
    "Frederick": "M",
    "Albert": "M",
    "Arianna": "F",
    "Gianna": "F",
    "Kyra": "F",
    "Azora Kiara": "F",
    "Azariah": "F",
    "Ariana": "F",
    "Azaria": "F",
    "Aiden": "M",
    "Malachi": "M",
    "thaniel": "M",
    "Joshua": "M",
    "Josiah": "M",
    "Zahir": "M",
    "than": "M",
    "Jouri": "F",
    "Naya": "F",
    "Mira": "F",
    "Lianne": "F",
    "Leen": "F",
    "Zina": "F",
    "Wateen": "F",
    "Tuleen": "F",
    "Karam": "M",
    "Shahem": "M",
    "Jad": "M",
    "Hashem": "M",
    "Hussa": "F",
    "Sherifa": "F",
    "Aisha": "F",
    "Lulwa": "F",
    "Shaikha": "F",
    "Fahad": "M",
    "Yousef": "M",
    "Abdulaziz": "M",
    "Faisal": "M",
    "Bader": "M",
    "Layla": "F",
    "Christina": "F",
    "Amal": "F",
    "Elie": "M",
    "Christian": "M",
    "Joe": "M",
    "Frieda": "F",
    "Melina": "F",
    "Elyas": "M",
    "Leano": "M",
    "Nelio": "M",
    "Raphael": "M",
    "Rafael": "M",
    "Valentin": "M",
    "Sofija": "F",
    "Emilija": "F",
    "Luknė": "F",
    "Amelija": "F",
    "Kamilė": "F",
    "Lėja": "F",
    "Gabija": "F",
    "Patricija": "F",
    "Elija": "F",
    "Liepa": "F",
    "Markas": "M",
    "Benas": "M",
    "Jokūbas": "M",
    "Dominykas": "M",
    "Herkus": "M",
    "Matas": "M",
    "Kajus": "M",
    "Adomas": "M",
    "Amy": "F",
    "Tom": "M",
    "Alise": "F",
    "Amēlija": "F",
    "Dārta": "F",
    "Elza": "F",
    "Marks": "M",
    "Roberts": "M",
    "Gustavs": "M",
    "Jēkabs": "M",
    "Emīls": "M",
    "Kārlis": "M",
    "Adrians": "M",
    "Daniels": "M",
    "Ralfs": "M",
    "Rania": "F",
    "Hoda": "F",
    "Mona": "F",
    "Eisha": "F",
    "Nesreen": "F",
    "Inès": "F",
    "Noûr": "F",
    "Assia": "F",
    "Aïcha": "F",
    "Amira": "F",
    "Naïm": "M",
    "Ayoub": "M",
    "Younès": "M",
    "Wassim": "M",
    "Amine": "M",
    "Stella": "F",
    "Aaron": "M",
    "Daria": "F",
    "Anastasia": "F",
    "Alexandra": "F",
    "Evelina": "F",
    "Matei": "M",
    "Maxim": "M",
    "Bogdan": "M",
    "Alexandru": "M",
    "Damian": "M",
    "Artiom": "M",
    "Ion": "M",
    "Jelena": "F",
    "Milica": "F",
    "Marija": "F",
    "Ivana": "F",
    "Milena": "F",
    "Dragana": "F",
    "Radmila": "F",
    "Vesna": "F",
    "Ljiljana": "F",
    "Nikola": "M",
    "Marko": "M",
    "Dragan": "M",
    "Miloš": "M",
    "Zoran": "M",
    "Milan": "M",
    "Aleksandar": "M",
    "Bisera": "F",
    "Jovana": "F",
    "Darija": "F",
    "Damjan": "M",
    "Mihail": "M",
    "Jovan": "M",
    "Stefan": "M",
    "Fatoumata": "F",
    "Aminata": "F",
    "Hawa": "F",
    "Awa": "F",
    "Oumou": "F",
    "Djeneba": "F",
    "Bintou": "F",
    "Fanta": "F",
    "Kadiatou": "F",
    "Mamadou": "M",
    "Moussa": "M",
    "Mahamadou": "M",
    "Adama": "M",
    "Bakary": "M",
    "Abdoulaye": "M",
    "Modibo": "M",
    "Oumar": "M",
    "Sekou": "M",
    "Souleymane": "M",
    "Odval": "F",
    "Bolormaa": "F",
    "Bayarmaa": "F",
    "Oyunbileg": "F",
    "Khongordzol": "F",
    "Naranbaatar": "M",
    "Batkhaаn": "M",
    "Baаtar": "M",
    "Chuluun": "M",
    "Sukhbaаtar": "M",
    "Nina": "F",
    "Regina": "F",
    "María José": "F",
    "Ximena": "F",
    "Camila": "F",
    "María Fernanda": "F",
    "Renata": "F",
    "Sebastián": "M",
    "Leordo": "M",
    "Diego": "M",
    "Wan": "M",
    "Nurul": "F",
    "Aisyah": "F",
    "Siti": "F",
    "Dhia": "F",
    "Naura": "F",
    "Ayra": "F",
    "Puteri": "F",
    "Muhamad": "M",
    "Iman": "M",
    "Harraz": "M",
    "Izz": "M",
    "Umar": "M",
    "Aariz": "M",
    "Yara": "F",
    "Saar": "F",
    "Tess": "F",
    "Noor": "F",
    "Mees": "M",
    "Levi": "M",
    "Sem": "M",
    "Iben": "F",
    "Isak": "M",
    "Shristi": "F",
    "Sunita": "F",
    "Rabina": "F",
    "Asmita": "F",
    "Niharika": "F",
    "Binita": "F",
    "Aasha": "F",
    "Kabita": "F",
    "Sita": "F",
    "Gita": "F",
    "Kiran": "M",
    "Bishal": "M",
    "Bibek": "M",
    "Siddhartha": "M",
    "Manish": "M",
    "Mahesh": "M",
    "Kamal": "M",
    "Prem": "M",
    "Prakash": "M",
    "Maia": "F",
    "Amaia": "F",
    "Kaia": "F",
    "Amara": "F",
    "Kora": "F",
    "Nikau": "M",
    "Koa": "M",
    "Keanu": "M",
    "Mikaere": "M",
    "Manaia": "M",
    "Kairo": "M",
    "Kiwa": "M",
    "Harper": "F",
    "Eithan": "M",
    "Alessia": "F",
    "Zoe": "F",
    "Luana": "F",
    "Tiare": "F",
    "Hinano": "F",
    "Poema": "F",
    "Maeva": "F",
    "Hina": "F",
    "Vaea": "F",
    "Titaua": "F",
    "Moea": "F",
    "Moeata": "F",
    "Tarita": "F",
    "Titaina": "F",
    "Teura": "F",
    "Heikapu": "F",
    "Mareva": "F",
    "Hiro": "M",
    "Teiki": "M",
    "Moana": "M",
    "Manua": "M",
    "Marama": "M",
    "Teiva": "M",
    "Teva": "M",
    "Maui": "M",
    "Tehei": "M",
    "Tamatoa": "M",
    "Ioane": "M",
    "Tapuarii": "M",
    "Althea": "F",
    "Angel": "F",
    "Samantha": "F",
    "Nathalie": "F",
    "Princess": "F",
    "Angela": "F",
    "Nathaniel": "M",
    "Ezekiel": "M",
    "Ethan": "M",
    "Angelo": "M",
    "Matthew": "M",
    "Zion": "M",
    "Fozia": "F",
    "Bismah": "F",
    "Sobia": "F",
    "Farrah": "F",
    "Farzana": "F",
    "Ayesha": "F",
    "Sakeena": "F",
    "Zainab": "F",
    "Hussain": "M",
    "Usman": "M",
    "Zahid": "M",
    "Shahid": "M",
    "Saqib": "M",
    "Nomaan": "M",
    "Zofia": "F",
    "Zuzanna": "F",
    "Maja": "F",
    "Oliwia": "F",
    "Alicja": "F",
    "Pola": "F",
    "Antoni": "M",
    "Aleksander": "M",
    "Franciszek": "M",
    "Nikodem": "M",
    "Stanisław": "M",
    "Mikołaj": "M",
    "Szymon": "M",
    "Nicolás": "M",
    "Leonor": "F",
    "Benedita": "F",
    "Carolina": "F",
    "Beatriz": "F",
    "Margarida": "F",
    "Afonso": "M",
    "Duarte": "M",
    "Lourenço": "M",
    "Martim": "M",
    "Ramona": "F",
    "Concepción": "F",
    "Mabel": "F",
    "Raquel": "F",
    "Noemí": "F",
    "Ramón": "M",
    "Javier": "M",
    "César": "M",
    "Andreea": "F",
    "Mirjana": "F",
    "Snežana": "F",
    "Gordana": "F",
    "Goran": "M",
    "Dušan": "M",
    "Dejan": "M",
    "Yelena": "F",
    "Olga": "F",
    "Natalia": "F",
    "Yekaterina": "F",
    "Tatiana": "F",
    "Irina": "F",
    "Yulia": "F",
    "Sergei": "M",
    "Dmitry": "M",
    "Andrei": "M",
    "Alexey": "M",
    "Evgeny": "M",
    "Mikhail": "M",
    "Artyom": "M",
    "Sofiya": "F",
    "Mariya": "F",
    "Viktoriya": "F",
    "Polina": "F",
    "Elizaveta": "F",
    "Varvara": "F",
    "Lev": "M",
    "Matvey": "M",
    "Daniil": "M",
    "Latifa": "F",
    "Hessa": "F",
    "Maysoun": "F",
    "Nouf": "F",
    "Reema": "F",
    "Alanoud": "F",
    "Abdulrahman": "M",
    "Turki": "M",
    "Bandar": "M",
    "Zala": "F",
    "Julija": "F",
    "Ajda": "F",
    "Vita": "F",
    "Lana": "F",
    "Neža": "F",
    "Nik": "M",
    "Lan": "M",
    "Tim": "M",
    "Lovro": "M",
    "Žan": "M",
    "Viktória": "F",
    "Natália": "F",
    "Nela": "F",
    "Sára": "F",
    "Michal": "M",
    "Richard": "M",
    "Astrid": "F",
    "Vera": "F",
    "Selma": "F",
    "Nils": "M",
    "Valter": "M",
    "Somchai": "M",
    "Somsak": "M",
    "Somporn": "M",
    "Somboon": "M",
    "Prasert": "M",
    "Sumayah": "F",
    "Asiya": "F",
    "Oisha": "F",
    "Googoosh": "F",
    "Anohito": "F",
    "Indira": "F",
    "Yusuf": "M",
    "Abdullo": "M",
    "Abubakr": "M",
    "Shayma": "F",
    "Khawla": "F",
    "Mehdi": "M",
    "Aziz": "M",
    "Ayşe": "F",
    "Emine": "F",
    "Hatice": "F",
    "Zeynep": "F",
    "Elif": "F",
    "Meryem": "F",
    "Şerife": "F",
    "Zehra": "F",
    "Sultan": "F",
    "Mehmet": "M",
    "Ahmet": "M",
    "Hüseyin": "M",
    "İsmail": "M",
    "Osman": "M",
    "Asel": "F",
    "Asya": "F",
    "Defne": "F",
    "Nehir": "F",
    "Azra": "F",
    "Zümra": "F",
    "Eylül": "F",
    "Ecrin": "F",
    "Alparslan": "M",
    "Miraç": "M",
    "Ömer Asaf": "M",
    "Eymen": "M",
    "Göktug": "M",
    "Ömer": "M",
    "Aras": "M",
    "Ali Asaf": "M",
    "Anastasiya": "F",
    "Veronika": "F",
    "Oleksandra": "F",
    "Milana": "F",
    "Yeva": "F",
    "Solomiya": "F",
    "Artem": "M",
    "Dmytro": "M",
    "Maksym": "M",
    "Mykhaylo": "M",
    "Danylo": "M",
    "Vladyslav": "M",
    "Oleksandr": "M",
    "Andriy": "M",
    "Linda": "F",
    "Barbara": "F",
    "Jennifer": "F",
    "Susan": "F",
    "Margaret": "F",
    "Dorothy": "F",
    "Robert": "M",
    "Michael": "M",
    "Charles": "M",
    "Joseph": "M",
    "Evelyn": "F",
    "Elijah": "M",
    "Nicole": "F",
    "Diego Alejandro": "M",
    "Daniel Alejandro": "M",
    "Juan Andrés": "M",
    "Melokuhle": "M",
    "Omphile": "M",
    "Iminathi": "F",
    "Lisakhanya": "F",
    "Lethabo": "M",
    "Amahle": "F",
    "Lesedi": "F",
    "Rethabile": "F",
    "Lethokuhle": "M",
    "Asemahle": "F",
    "Lubanzi": "M",
    "Junior": "M",
    "Siphosethu": "M",
    "Lwandle": "M",
    "Banele": "M",
    "Ofentse": "M",
    "Viktoria": "F",
    "Nikol": "F",
    "Raya": "F",
    "Yoana": "F",
    "Aleksandra": "F",
    "Simona": "F",
    "Georgi": "M",
    "Kaloyan": "M",
    "Boris": "M",
    "Dimitar": "M",
    "Teodor": "M",
    "Viktor": "M",
    "Ruòxī": "F",
    "Yīnuò": "F",
    "Yìhán": "F",
    "Zǐhán": "F",
    "Yǐmò": "F",
    "Yǔtóng": "F",
    "Xīnyí": "F",
    "Yǔxī": "F",
    "Mùchén": "M",
    "Hàoyǔ": "M",
    "Míngzé": "M",
    "Yìchén": "M",
    "Yǔzé": "M",
    "Hàorán": "M",
    "Yìzé": "M",
    "Yǔxuān": "M",
    "Mùyáng": "M",
    "Eleni": "F",
    "Androula": "F",
    "Georgia": "F",
    "Panagiota": "F",
    "Katerina": "F",
    "Ioanna": "F",
    "Kyriaki": "F",
    "Andreas": "M",
    "Georgios": "M",
    "Konstantinos": "M",
    "Christos": "M",
    "Nikolaos": "M",
    "Michalis": "M",
    "Panagiotis": "M",
    "Ioannis": "M",
    "Marios": "M",
    "Dimitrios": "M",
    "Mariami": "F",
    "Elene": "F",
    "Barbare": "F",
    "Lile": "F",
    "Nia": "F",
    "Nutsa": "F",
    "Sesili": "F",
    "Andria": "M",
    "Giorgi": "M",
    "Aleksandre": "M",
    "Nikoloz": "M",
    "Demetre": "M",
    "Gabor": "M",
    "Aikaterini": "F",
    "Vasiliki": "F",
    "Angeliki": "F",
    "Gogo": "F",
    "Dimitra": "F",
    "Konstantina": "F",
    "Paraskevi": "F",
    "Vasileios": "M",
    "Athanasios": "M",
    "Saliha": "F",
    "Rayana": "F",
    "Fátima": "F",
    "Aliya": "F",
    "Safiya": "F",
    "Aruuzat": "F",
    "Hadicha": "F",
    "Aruuke": "F",
    "Alikhan": "M",
    "Alinur": "M",
    "Nurislam": "M",
    "Emir": "M",
    "Ji-an": "F",
    "Ha-yoon": "F",
    "Seo-ah": "F",
    "Ha-eun": "F",
    "Seo-yun": "F",
    "Ha-rin": "F",
    "Ji-yoo": "F",
    "Ji-woo": "F",
    "Soo-ah": "F",
    "Ji-a": "F",
    "Seo-jun": "M",
    "Ha-joon": "M",
    "Do-yun": "M",
    "Eun-woo": "M",
    "Si-woo": "M",
    "Ji-ho": "M",
    "Ye-jun": "M",
    "Yu-jun": "M",
    "Ju-won": "M",
    "Min-jun": "M",
    "Mädïna": "F",
    "Asilim": "F",
    "Ayşa": "F",
    "Ayzere": "F",
    "Tomyris": "F",
    "Ayim": "F",
    "Aisultan": "M",
    "Aldiyar": "M",
    "Ramazan": "M",
    "Shu-fen": "F",
    "Shu-hui": "F",
    "Mei-ling": "F",
    "Ya-ting": "F",
    "Mei-hui": "F",
    "Li-hua": "F",
    "Shu-chuan": "F",
    "Shu-chen": "F",
    "I-chun": "F",
    "Shu-hua": "F",
    "Chia-hao": "M",
    "Chih-ming": "M",
    "Chun-chieh": "M",
    "Chien-hung": "M",
    "Chun-hung": "M",
    "Chih-hao": "M",
    "Chih-wei": "M",
    "Wen-Hsiung": "M",
    "Chin-lung": "M",
    "Chih-chiang": "M",
    "Ao": "M",
    "Sō": "M",
    "Aoi": "M",
    "Nagi": "M",
    "Nagisa": "M",
    "Ren": "M",
    "Hinato": "M",
    "Haruto": "M",
    "Minato": "M",
    "Sōma": "M",
    "Fūma": "M",
    "Itsuki": "M",
    "Tatsuki": "M",
    "Yamato": "M",
    "Yūma": "M",
    "Haruma": "M",
    "Haru": "M",
    "Dan": "M",
    "Hinata": "F",
    "Himari": "F",
    "Rin": "F",
    "Uta": "F",
    "Haruna": "F",
    "Yuna": "F",
    "Yuina": "F",
    "Yūna": "F",
    "An": "F",
    "Anzu": "F",
    "Mio": "F",
    "Rei": "F",
    "Yua": "F",
    "Mei": "F",
    "Riko": "F",
    "Sakura": "F"
};
var FNkeys = Object.keys(firstNames);

var lastNames = {
    "Grigoryan": "AM",
    "Harutyunyan": "AM",
    "Sargsyan": "AM",
    "Hovhannisyan": "AM",
    "Khachatryan": "AM",
    "Hakobyan": "AM",
    "Petrosyan": "AM",
    "Vardanyan": "AM",
    "Gevorgyan": "AM",
    "Karapetyan": "AM",
    "Mkrtchyan": "AM",
    "Ghazaryan": "AM",
    "Manukyan": "AM",
    "Avetisyan": "AM",
    "Poghosyan": "AM",
    "Martirosyan": "AM",
    "Sahakyan": "AM",
    "Arakelyan": "AM",
    "Margaryan": "AM",
    "Davtyan": "AM",
    "Mammadov": "AZ",
    "Aliyev": "GE",
    "Huseynov": "AZ",
    "Hasanov": "AZ",
    "Guliyev": "AZ",
    "Ismayilov": "AZ",
    "Ahmadov": "AZ",
    "Abdullayev": "AZ",
    "Abbasov": "AZ",
    "Jafarov": "AZ",
    "Akter": "BD",
    "Islam": "BD",
    "Khatun": "BD",
    "Hossain": "BD",
    "Rahman": "BD",
    "Ahmed": "BD",
    "Keo": "KH",
    "Khat": "KH",
    "Khay": "KH",
    "Khiev": "KH",
    "Khlot": "KH",
    "Kim": "VN",
    "Chhan": "KH",
    "Bird": "KH",
    "Chen": "KR",
    "Chhorn": "KH",
    "Chea": "KH",
    "Cheam": "KH",
    "Chin": "SR",
    "Chim": "KH",
    "Chey": "KH",
    "Chhet": "KH",
    "Chhim": "KH",
    "Nhek": "KH",
    "Duong": "KH",
    "Dith": "KH",
    "Din": "KH",
    "Dul": "KH",
    "Droplets": "KH",
    "Tang": "KH",
    "Tat": "KH",
    "Taing": "KH",
    "Ty": "KH",
    "Tep": "KH",
    "Thy": "KH",
    "Khmer": "KH",
    "Pang": "KH",
    "Pok": "KH",
    "Bun": "KH",
    "Pen": "KH",
    "Phan": "VN",
    "means": "KH",
    "Phy": "KH",
    "Ma": "CN",
    "Mean": "KH",
    "Meas": "KH",
    "Muy": "KH",
    "Mul": "KH",
    "Meng": "KH",
    "Mao": "KH",
    "Yos": "KH",
    "Yun": "KR",
    "Yu": "KR",
    "Ros": "KH",
    "Lim": "TW",
    "Vang": "TW",
    "Vong": "TW",
    "Sor": "KH",
    "Sang": "KH",
    "Sam": "KH",
    "Sat": "KH",
    "San": "KH",
    "Say": "KH",
    "Sin": "KR",
    "Son": "KR",
    "Sok": "KH",
    "Song": "KR",
    "Suy": "KH",
    "So": "KH",
    "Su": "KH",
    "Soun": "KH",
    "Sieng": "KH",
    "Seng": "KH",
    "Sen": "KH",
    "Som": "KH",
    "Hong": "KR",
    "Hun": "KH",
    "Ho": "CN",
    "Long": "US",
    "Ang": "KH",
    "Im": "KR",
    "Ong": "KH",
    "Uch": "KH",
    "Uy": "KH",
    "Eam": "KH",
    "Iv": "KH",
    "Um": "KR",
    "Ek": "KH",
    "Ok": "KH",
    "Om": "KH",
    "Wáng": "TW",
    "Wong": "SR",
    "Lǐ": "TW",
    "Lee": "AU",
    "Zhāng": "TW",
    "Cheung": "TW",
    "Liú": "TW",
    "Lau": "TW",
    "Chén": "TW",
    "Chan": "TW",
    "Yáng": "TW",
    "Yeung": "TW",
    "Huáng": "TW",
    "Zhào": "CN",
    "Chiu": "CN",
    "Ng": "TW",
    "Wú": "TW",
    "Zhōu": "CN",
    "Chow": "CN",
    "Tsui": "CN",
    "Xú": "CN",
    "Suen": "CN",
    "Sūn": "CN",
    "Mǎ": "CN",
    "Chu": "KR",
    "Zhū": "CN",
    "Hú": "CN",
    "Wu": "TW",
    "Guō": "CN",
    "Kwok": "CN",
    "Hé": "CN",
    "Lam": "TW",
    "Lín": "TW",
    "Gāo": "CN",
    "Ko": "KR",
    "Law": "CN",
    "Luó": "CN",
    "Beridze": "GE",
    "Mamedovi": "GE",
    "Mamedov": "GE",
    "Kapanadze": "GE",
    "Gelashvili": "GE",
    "Alievi": "GE",
    "Maisuradze": "GE",
    "Giorgadze": "GE",
    "Lomidze": "GE",
    "Tsiklauri": "GE",
    "Bolkvadze": "GE",
    "Kvaratskhelia": "GE",
    "Nozadze": "GE",
    "Khutsishvili": "GE",
    "Shengelia": "GE",
    "Abuladze": "GE",
    "Mikeladze": "GE",
    "Tabatadze": "GE",
    "Mchedlishvili": "GE",
    "Bairamov": "GE",
    "Bairamovi": "GE",
    "Gogoladze": "GE",
    "Devi": "FJ",
    "Kumar": "FJ",
    "Singh": "SR",
    "Sharma": "NZ",
    "Ali": "FJ",
    "Yadav": "NP",
    "Patel": "NZ",
    "Cohen": "AR",
    "Levi": "IL",
    "Levy": "IL",
    "Mizrahi": "IL",
    "Mizrachi": "IL",
    "Peretz": "IL",
    "Biton": "IL",
    "Dahan": "IL",
    "Avraham": "IL",
    "Friedman": "IL",
    "Malka": "IL",
    "Malcah": "IL",
    "Azoulay": "IL",
    "Katz": "IL",
    "Yosef": "IL",
    "David": "FR",
    "Amar": "IL",
    "Omer": "IL",
    "Ochion": "IL",
    "Ohayon": "IL",
    "Hadad": "IL",
    "Chadad": "IL",
    "Gabai": "IL",
    "Ben-David": "IL",
    "Edri": "IL",
    "Edry": "IL",
    "Adrei": "IL",
    "Adary": "IL",
    "Levin": "IL",
    "Tal": "IL",
    "Klein": "LU",
    "Khen": "IL",
    "Shapira": "IL",
    "Chazan": "IL",
    "Hazan": "IL",
    "Moshe": "IL",
    "Ashkenazi": "IL",
    "Ohana": "IL",
    "Segal": "IL",
    "Segel": "IL",
    "Golan": "IL",
    "Satō": "JP",
    "Suzuki": "JP",
    "Takahashi": "JP",
    "Tanaka": "JP",
    "Watanabe": "JP",
    "Itō": "JP",
    "Nakamura": "JP",
    "Kobayashi": "JP",
    "Yamamoto": "JP",
    "Katō": "JP",
    "Yoshida": "JP",
    "Yamada": "JP",
    "Sasaki": "JP",
    "Yamaguchi": "JP",
    "Matsumoto": "JP",
    "Inoue": "JP",
    "Kimura": "JP",
    "Shimizu": "JP",
    "Hayashi": "JP",
    "Saitō": "JP",
    "Yamasaki": "JP",
    "Yamazaki": "JP",
    "Nakajima": "JP",
    "Nakashima": "JP",
    "Mori": "JP",
    "Abe": "JP",
    "Ikeda": "JP",
    "Hashimoto": "JP",
    "Ishikawa": "JP",
    "Yamashita": "JP",
    "Ogawa": "JP",
    "Ishii": "JP",
    "Hasegawa": "JP",
    "Gotō": "JP",
    "Okada": "JP",
    "Kondō": "JP",
    "Maeda": "JP",
    "Fujita": "JP",
    "Endō": "JP",
    "Aoki": "JP",
    "Sakamoto": "JP",
    "Murakami": "JP",
    "Ōta": "JP",
    "Kaneko": "JP",
    "Fujii": "JP",
    "Fukuda": "JP",
    "Nishimura": "JP",
    "Miura": "JP",
    "Takeuchi": "JP",
    "Nakagawa": "JP",
    "Okamoto": "JP",
    "Matsuda": "JP",
    "Harada": "JP",
    "Nakano": "JP",
    "Ono": "JP",
    "Tamura": "JP",
    "Fujiwara": "JP",
    "Fujihara": "JP",
    "Nakayama": "JP",
    "Ishida": "JP",
    "Kojima": "JP",
    "Wada": "JP",
    "Morita": "JP",
    "Uchida": "JP",
    "Shibata": "JP",
    "Sakai": "JP",
    "Hara": "JP",
    "Takagi": "JP",
    "Takaki": "JP",
    "Yokoyama": "JP",
    "Andō": "JP",
    "Miyazaki": "JP",
    "Miyasaki": "JP",
    "Ueta": "JP",
    "Ueda": "JP",
    "Shimada": "JP",
    "Kudō": "JP",
    "Ōno": "JP",
    "Miyamoto": "JP",
    "Sugiyama": "JP",
    "Imai": "JP",
    "Maruyama": "JP",
    "Masuda": "JP",
    "Takata": "JP",
    "Takada": "JP",
    "Murata": "JP",
    "Hirano": "JP",
    "Ōtsuka": "JP",
    "Sugahara": "JP",
    "Sugawara": "JP",
    "Taketa": "JP",
    "Takeda": "JP",
    "Arai": "JP",
    "Koyama": "JP",
    "Oyama": "JP",
    "Noguchi": "JP",
    "Sakurai": "JP",
    "Chiba": "JP",
    "Iwasaki": "JP",
    "Sano": "JP",
    "Taniguchi": "JP",
    "Ueno": "JP",
    "Matsui": "JP",
    "Kōno": "JP",
    "Kawano": "JP",
    "Ichikawa": "JP",
    "Watabe": "JP",
    "Nomura": "JP",
    "Kikuchi": "JP",
    "Kinoshita": "JP",
    "Ahmetov": "KZ",
    "Omarov": "KZ",
    "Ospanov": "KZ",
    "Ivanov": "MK",
    "Aliev": "KZ",
    "Suleimenov": "KZ",
    "Iskakov": "KZ",
    "Abdrahmanov": "KZ",
    "Ibragimov": "KZ",
    "Kaliev": "KZ",
    "Sadykov": "KZ",
    "Ibraev": "KZ",
    "Kuznetsov": "EE",
    "Popov": "RU",
    "Smagulov": "KZ",
    "Abdullaev": "KZ",
    "Isaev": "KZ",
    "Sultanov": "KZ",
    "Iusupov": "KZ",
    "Ismailov": "KZ",
    "Nurgaliev": "KZ",
    "Karimov": "KZ",
    "Серик": "KZ",
    "Li": "TW",
    "Tsoi": "TW",
    "Amangeldy": "KZ",
    "Bolat": "KZ",
    "Bondarenko": "UA",
    "Marat": "KZ",
    "Серикбай": "KZ",
    "Murat": "KZ",
    "Kusainov": "KZ",
    "Gim": "KR",
    "Ghim": "KR",
    "Yi": "KR",
    "Rhee": "KR",
    "Pak": "KR",
    "Bak": "KR",
    "Park": "KR",
    "Choy": "TW",
    "Choe": "KR",
    "Joy": "KR",
    "Choi": "TW",
    "Young": "US",
    "Jung": "KR",
    "Chung": "KR",
    "Cheong": "TW",
    "Jeong": "KR",
    "Gang": "KR",
    "Kang": "KR",
    "Ghang": "KR",
    "Jo": "KR",
    "Cho": "KR",
    "Joe": "KR",
    "Yoon": "KR",
    "Youn": "KR",
    "Jang": "KR",
    "Chang": "TW",
    "Rim": "KR",
    "Rhim": "KR",
    "Han": "KR",
    "Oh": "KR",
    "O": "KR",
    "Seoh": "KR",
    "Suh": "KR",
    "Seo": "KR",
    "Shin": "KR",
    "Gwon": "KR",
    "Kuen": "KR",
    "Kwon": "KR",
    "Hwang": "KR",
    "Huang": "TW",
    "An": "KR",
    "Ahn": "KR",
    "Ryoo": "KR",
    "Yoo": "KR",
    "Ryu": "KR",
    "Cheon": "KR",
    "Jun": "KR",
    "Chun": "TW",
    "Jeon": "KR",
    "Koh": "KR",
    "Goh": "TW",
    "Go": "KR",
    "Mon": "KR",
    "Munn": "KR",
    "Mun": "KR",
    "Moon": "KR",
    "Yang": "TW",
    "Ryang": "KR",
    "Sohn": "KR",
    "Sonn": "KR",
    "Pae": "KR",
    "Bae": "KR",
    "Bai": "KR",
    "Pai": "KR",
    "Bhak": "KR",
    "Paik": "KR",
    "Baek": "KR",
    "Phak": "KR",
    "Hur": "KR",
    "Heo": "KR",
    "Her": "KR",
    "Hui": "KR",
    "Liu": "TW",
    "Yau": "KR",
    "Nan": "KR",
    "Nham": "KR",
    "Nam": "KR",
    "Shen": "KR",
    "Sim": "KR",
    "Shim": "KR",
    "Roh": "KR",
    "No": "KR",
    "Noh": "KR",
    "Ha": "KR",
    "Hah": "KR",
    "Gwak": "KR",
    "Kwak": "KR",
    "Koak": "KR",
    "Seong": "KR",
    "Sung": "KR",
    "Shung": "KR",
    "Shong": "KR",
    "Cha": "KR",
    "Zhu": "KR",
    "Juu": "KR",
    "Ju": "KR",
    "Choo": "KR",
    "Zuu": "KR",
    "Joo": "KR",
    "Woo": "TW",
    "U": "KR",
    "Goo": "KR",
    "Gu": "KR",
    "Koo": "KR",
    "Yim": "KR",
    "La": "KR",
    "Na": "KR",
    "Ra": "KR",
    "Min": "KR",
    "Jean": "KR",
    "Jin": "KR",
    "Jen": "KR",
    "Ji": "KR",
    "Jee": "KR",
    "Eom": "KR",
    "Uhm": "KR",
    "Chaudhary": "NP",
    "Chowdhury": "NP",
    "Tamang": "NP",
    "Gurung": "NP",
    "Thapa": "NP",
    "Rana": "NP",
    "Magar": "NP",
    "Rai": "NP",
    "Shrestha": "NP",
    "Lama": "NP",
    "Chetry": "NP",
    "Chhetri": "NP",
    "Shah": "NP",
    "Sah ": "NP",
    "Bishwakarma": "NP",
    "Maharjan": "NP",
    "Nepali ": "NP",
    "Pariyar": "NP",
    "Pokharel": "NP",
    "Pokhrel ": "NP",
    "Tharu": "NP",
    "dela Cruz": "PH",
    "Garcia": "US",
    "Reyes": "PE",
    "Ramos": "PE",
    "Mendoza": "PE",
    "Santos": "BR",
    "Flores": "PE",
    "Gonzales": "PH",
    "Bautista": "PH",
    "Villanueva": "PH",
    "Fernandez": "PH",
    "Cruz": "US",
    "de Guzman": "PH",
    "Lopez": "US",
    "Perez": "US",
    "Castillo": "PE",
    "Francisco": "PH",
    "Rivera": "CL",
    "Aquino": "PH",
    "Castro": "PE",
    "Sanchez": "US",
    "Torres": "PE",
    "de Leon": "PH",
    "Domingo": "PH",
    "Martinez": "US",
    "Rodriguez": "US",
    "Santiago": "PH",
    "Soriano": "PH",
    "delos Santos": "PH",
    "Diaz": "US",
    "Hernandez": "US",
    "Tolentino": "PH",
    "Valdez": "MX",
    "Ramirez": "US",
    "Morales": "PE",
    "Mercado": "PH",
    "Tan": "PH",
    "Aguilar": "AR",
    "Navarro": "CL",
    "Manalo": "PH",
    "Gomez": "US",
    "Dizon": "PH",
    "del Rosario": "PH",
    "Javier": "PH",
    "Corpuz": "PH",
    "Gutierrez": "US",
    "Salvador": "PH",
    "Velasco": "PH",
    "Miranda": "CL",
    "Smirnov": "EE",
    "Sokolov": "RU",
    "Lebedev": "RU",
    "Kozlov": "RU",
    "Novikov": "RU",
    "Morozov": "RU",
    "Petrov": "EE",
    "Volkov": "RU",
    "Solovyov": "RU",
    "Vasilyev": "RU",
    "Zaytsev": "RU",
    "Pavlov": "EE",
    "Semyonov": "RU",
    "Golubev": "RU",
    "Vinogradov": "RU",
    "Bogdanov": "MK",
    "Vorobyov": "RU",
    "Perera": "LK",
    "Fernando": "LK",
    "de Silva": "LK",
    "Bandara": "LK",
    "Kumara": "LK",
    "Dissanayake": "LK",
    "Mohamed": "LK",
    "Gamage": "LK",
    "Liyanage": "LK",
    "Jayasinghe": "LK",
    "Ranasinghe": "LK",
    "Herath": "LK",
    "Weerasinghe": "LK",
    "Peiris": "LK",
    "Rathnayake": "LK",
    "Wickramasinghe": "LK",
    "Wijesinghe": "LK",
    "Hettiarachchi": "LK",
    "Nanayakkara": "LK",
    "Ahamed": "LK",
    "Rajapaksha": "LK",
    "Mendis": "LK",
    "Pathirana": "LK",
    "Ekanayake": "LK",
    "Gunasekara": "LK",
    "Dias": "BR",
    "Sampath": "LK",
    "Amarasinghe": "LK",
    "Ratnayake": "LK",
    "Chathuranga": "LK",
    "Senanayake": "LK",
    "Samarasinghe": "LK",
    "Lakmal": "LK",
    "Munasinghe": "LK",
    "Rodrigo": "LK",
    "Seneviratne": "LK",
    "Rathnayaka": "LK",
    "Edirisinghe": "LK",
    "Jayawardena": "LK",
    "Fonseka": "LK",
    "Sanjeewa": "LK",
    "Gunawardana": "LK",
    "Gunawardena": "LK",
    "Karunaratne": "LK",
    "Jayaweera": "LK",
    "Jayasekara": "LK",
    "Ranaweera": "LK",
    "Jayawardana": "LK",
    "Jayasuriya": "LK",
    "Madusanka": "LK",
    "Yılmaz": "TR",
    "Kaya": "TR",
    "Demir": "TR",
    "Şahin": "TR",
    "Çelik": "TR",
    "Yıldız": "TR",
    "Yıldırım": "TR",
    "Öztürk": "TR",
    "Aydın": "TR",
    "Özdemir": "TR",
    "Arslan": "TR",
    "Doğan": "TR",
    "Kılıç": "TR",
    "Aslan": "TR",
    "Çetin": "TR",
    "Kara": "TR",
    "Koç": "TR",
    "Kurt": "TR",
    "Özkan": "TR",
    "Şimşek": "TR",
    "Nguyễn": "VN",
    "Trần": "VN",
    "Lê": "VN",
    "Phạm": "VN",
    "Huỳnh/Hoàng": "VN",
    "Vũ/Võ": "VN",
    "Đặng": "VN",
    "Bùi": "VN",
    "Đỗ": "VN",
    "Hồ": "VN",
    "Ngô": "VN",
    "Dương": "VN",
    "Lý": "VN",
    "Phí": "VN",
    "Đào": "VN",
    "Đoàn": "VN",
    "Vương": "VN",
    "Trịnh": "VN",
    "Trương": "VN",
    "Lâm": "VN",
    "Phùng": "VN",
    "Mai": "VN",
    "Tô": "VN",
    "Hà": "VN",
    "Tạ": "VN",
    "Thân": "VN",
    "Trác": "VN",
    "Tống": "VN",
    "Hoa": "VN",
    "Khúc": "VN",
    "Từ": "VN",
    "Thường": "VN",
    "Tiêu": "VN",
    "Ngọ": "VN",
    "Quách": "VN",
    "Đàm": "VN",
    "Triệu": "VN",
    "Mạc": "VN",
    "Thái": "VN",
    "Lưu": "VN",
    "Thạch": "VN",
    "Lương": "VN",
    "Can": "TW",
    "Ting": "TW",
    "Ch'en": "TW",
    "Tân": "TW",
    "Lin": "SR",
    "Liem": "TW",
    "Lum": "TW",
    "Lîm": "TW",
    "Wang": "TW",
    "Ung": "TW",
    "Eng": "TW",
    "Zoeng": "TW",
    "Chong": "TW",
    "Tiong": "TW",
    "Teoh": "TW",
    "Teo": "TW",
    "Tiu": "TW",
    "Lei": "TW",
    "Lí": "TW",
    "Le": "TW",
    "Heng": "TW",
    "Ông": "TW",
    "Gô͘": "TW",
    "Ngô͘": "TW",
    "Gouw": "TW",
    "Low": "TW",
    "Lou": "TW",
    "Lâu": "TW",
    "Lao": "TW",
    "Ts'ai": "TW",
    "Chua": "TW",
    "Coi": "TW",
    "Tsay": "TW",
    "Cài": "TW",
    "Choa": "TW",
    "Chhoà": "TW",
    "Toy": "TW",
    "Chai": "TW",
    "Iû": "TW",
    "Joeng": "TW",
    "Eaw": "TW",
    "Ieong": "TW",
    "Yeong": "TW",
    "Hoxha": "AL",
    "Prifti": "AL",
    "Shehu": "AL",
    "Dervishi": "AL",
    "Bektashi": "AL",
    "Begu": "AL",
    "Gjoni": "AL",
    "Leka": "AL",
    "Murati": "AL",
    "Mehmeti": "AL",
    "Hysi": "AL",
    "Gjika": "AL",
    "Marku": "AL",
    "Kola": "AL",
    "Kolla": "AL",
    "Nikolla": "AL",
    "Hasani": "XK",
    "Kristi": "AL",
    "Kristo": "AL",
    "Luka": "AL",
    "Brahimi": "AL",
    "Sinani": "AL",
    "Thanasi": "AL",
    "Halili": "AL",
    "Abazi": "AL",
    "Dibra": "AL",
    "Laçi": "AL",
    "Shkodra": "AL",
    "Prishtina": "AL",
    "Delvina": "AL",
    "Koroveshi": "AL",
    "Përmeti": "AL",
    "Frashëri": "AL",
    "Gegaj": "AL",
    "Gega": "AL",
    "Toska": "AL",
    "Toskaj": "AL",
    "Çami": "AL",
    "Kelmendi": "AL",
    "Shkreli": "AL",
    "Berisha": "XK",
    "Krasniqi": "XK",
    "Gashi": "XK",
    "Kuqi": "AL",
    "Bardhi": "AL",
    "Gruber": "AT",
    "Huber": "CH",
    "Bauer": "AT",
    "Wagner": "LU",
    "Müller": "CH",
    "Pichler": "AT",
    "Steiner": "CH",
    "Moser": "CH",
    "Mayer": "AT",
    "Hofer": "AT",
    "Leitner": "AT",
    "Berger": "AT",
    "Fuchs": "AT",
    "Eder": "AT",
    "Fischer": "CH",
    "Schmid": "CH",
    "Winkler": "AT",
    "Weber": "CH",
    "Schwarz": "AT",
    "Maier": "AT",
    "Schneider": "CH",
    "Reiter": "AT",
    "Mayr": "AT",
    "Schmidt": "BR",
    "Wimmer": "AT",
    "Egger": "AT",
    "Brunner": "CH",
    "Lang": "AT",
    "Baumgartner": "AT",
    "Auer": "AT",
    "Binder": "AT",
    "Lechner": "AT",
    "Wolf": "AT",
    "Wallner": "AT",
    "Aigner": "AT",
    "Ebner": "AT",
    "Koller": "AT",
    "Lehner": "AT",
    "Haas": "AT",
    "Schuster": "AT",
    "Heilig": "AT",
    "Ivanoŭ": "BY",
    "Kazloŭ": "BY",
    "Kavalioŭ": "BY",
    "Kazloŭski": "BY",
    "Novik": "BY",
    "Peeters": "BE",
    "Janssens": "BE",
    "Maes": "BE",
    "Jacobs": "BE",
    "Mertens": "BE",
    "Willems": "BE",
    "Claes": "BE",
    "Goossens": "BE",
    "Wouters": "BE",
    "De Smet": "BE",
    "Dubois": "FR",
    "Lambert": "FR",
    "Dupont": "FR",
    "Martin": "AU",
    "Diallo": "BE",
    "Simon": "LU",
    "Dumont": "BE",
    "Leclercq": "BE",
    "Laurent": "FR",
    "Denis": "BE",
    "Lejeune": "BE",
    "Bah": "BE",
    "Barry": "BE",
    "Nguyen": "AU",
    "Sow": "BE",
    "Benali": "BE",
    "Hodžić": "BA",
    "Hadžić": "BA",
    "Čengić": "BA",
    "Delić": "BA",
    "Demirović": "BA",
    "Kovačević": "ME",
    "Tahirović": "BA",
    "Ferhatović": "BA",
    "Muratović": "BA",
    "Ibrahimović": "BA",
    "Hasanović": "BA",
    "Mehmedović": "BA",
    "Salihović": "BA",
    "Terzić": "BA",
    "Ademović": "BA",
    "Adilović": "BA",
    "Delemović": "BA",
    "Zukić": "BA",
    "Krličević": "BA",
    "Suljić": "BA",
    "Ahmetović": "BA",
    "Subotić": "BA",
    "Savić": "BA",
    "Popović": "ME",
    "Jovanović": "RS",
    "Petrović": "RS",
    "Đurić": "BA",
    "Babić": "HR",
    "Lukić": "BA",
    "Knežević": "HR",
    "Marković": "RS",
    "Ilić": "RS",
    "Đukić": "BA",
    "Vuković": "ME",
    "Vujić": "BA",
    "Simić": "BA",
    "Radić": "HR",
    "Nikolić": "RS",
    "Marić": "HR",
    "Mitrović": "BA",
    "Tomić": "HR",
    "Božić": "HR",
    "Golubović": "BA",
    "Mirković": "BA",
    "Ivanova": "BG",
    "Georgiev": "MK",
    "Georgieva": "BG",
    "Dimitrov": "MK",
    "Dimitrova": "BG",
    "Petrova": "BG",
    "Nikolov": "BG",
    "Nikolova": "BG",
    "Hristov": "BG",
    "Hristova": "BG",
    "Stoyanova": "BG",
    "Stoyanov": "BG",
    "Todorova": "BG",
    "Todorov": "BG",
    "Iliev": "BG",
    "Ilieva": "BG",
    "Angelov": "MK",
    "Angelova": "BG",
    "Horvat": "SI",
    "Jurić": "HR",
    "Novak": "SI",
    "Kovačić": "HR",
    "Matić": "HR",
    "Pavlović": "RS",
    "Kovač": "SI",
    "Blažević": "HR",
    "Grgić": "HR",
    "Pavić": "HR",
    "Perić": "HR",
    "Filipović": "HR",
    "Šarić": "HR",
    "Lovrić": "HR",
    "Vidović": "HR",
    "Perković": "HR",
    "Bošnjak": "HR",
    "Jukić": "HR",
    "Barišić": "HR",
    "Novák": "SK",
    "Nováková": "CZ",
    "Svobodová": "CZ",
    "Svoboda": "CZ",
    "Novotný": "CZ",
    "Novotná": "CZ",
    "Dvořáková": "CZ",
    "Dvořák": "CZ",
    "Černá": "CZ",
    "Černý": "CZ",
    "Procházková": "CZ",
    "Procházka": "CZ",
    "Kučera": "CZ",
    "Kučerová": "CZ",
    "Veselý": "CZ",
    "Veselá": "CZ",
    "Horáková": "CZ",
    "Horák": "CZ",
    "Němec": "CZ",
    "Němcová": "CZ",
    "Nielsen": "IS",
    "Jensen": "NO",
    "Hansen": "NO",
    "Pedersen": "NO",
    "Andersen": "NO",
    "Christensen": "DK",
    "Larsen": "NO",
    "Sørensen": "FO",
    "Rasmussen": "FO",
    "Jørgensen": "NO",
    "Petersen": "IS",
    "Madsen": "DK",
    "Kristensen": "DK",
    "Olsen": "NO",
    "Thomsen": "FO",
    "Christiansen": "DK",
    "Poulsen": "FO",
    "Johansen": "NO",
    "Møller": "DK",
    "Mortensen": "FO",
    "Joensen": "FO",
    "Jacobsen": "NO",
    "Johannesen": "FO",
    "Djurhuus": "FO",
    "Simonsen": "FO",
    "Danielsen": "FO",
    "Højgaard": "FO",
    "Mikkelsen": "FO",
    "Dam": "FO",
    "Tamm": "EE",
    "Saar": "EE",
    "Sepp": "EE",
    "Mägi": "EE",
    "Vassiljev": "EE",
    "Kask": "EE",
    "Kukk": "EE",
    "Rebane": "EE",
    "Karpin": "EE",
    "Ilves": "EE",
    "Mihhailov": "EE",
    "Pärn": "EE",
    "Semjonov": "EE",
    "Koppel": "EE",
    "Andrejev": "EE",
    "Aleksejev": "EE",
    "Korhonen": "FI",
    "Virtanen": "FI",
    "Mäkinen": "FI",
    "Nieminen": "FI",
    "Mäkelä": "FI",
    "Hämäläinen": "FI",
    "Laine": "FI",
    "Heikkinen": "FI",
    "Koskinen": "FI",
    "Järvinen": "FI",
    "Lehtonen": "FI",
    "Lehtinen": "FI",
    "Saarinen": "FI",
    "Salminen": "FI",
    "Heinonen": "FI",
    "Niemi": "FI",
    "Heikkilä": "FI",
    "Kinnunen": "FI",
    "Salonen": "FI",
    "Turunen": "FI",
    "Salo": "FI",
    "Laitinen": "FI",
    "Tuominen": "FI",
    "Rantanen": "FI",
    "Karjalainen": "FI",
    "Jokinen": "FI",
    "Mattila": "FI",
    "Savolainen": "FI",
    "Lahtinen": "FI",
    "Ahonen": "FI",
    "Bernard": "FR",
    "Thomas": "US",
    "Robert": "FR",
    "Richard": "FR",
    "Petit": "FR",
    "Durand": "FR",
    "Leroy": "FR",
    "Moreau": "FR",
    "Lefebvre": "FR",
    "Michel": "FR",
    "Bertrand": "FR",
    "Roux": "FR",
    "Vincent": "FR",
    "Fournier": "FR",
    "Morel": "FR",
    "Girard": "FR",
    "André": "FR",
    "Lefèvre": "FR",
    "Mercier": "FR",
    "Bonnet": "FR",
    "François": "FR",
    "Meyer": "CH",
    "Schulz": "DE",
    "Becker": "LU",
    "Hoffmann": "LU",
    "Samaras": "GR",
    "Papoutsis": "GR",
    "Kritikos": "GR",
    "Aivaliotis": "GR",
    "Kontos": "GR",
    "Mytaras": "GR",
    "Koufos": "GR",
    "Nagy": "SK",
    "Kovács": "SK",
    "Tóth": "SK",
    "Szabó": "SK",
    "Horváth": "SK",
    "Varga": "SK",
    "Kiss": "HU",
    "Molnár": "SK",
    "Németh": "HU",
    "Farkas": "HU",
    "Balogh": "HU",
    "Papp": "HU",
    "Lakatos": "HU",
    "Takács": "HU",
    "Juhász": "HU",
    "Mészáros": "HU",
    "Oláh": "SK",
    "Rácz": "HU",
    "Fekete": "HU",
    "Szilágyi": "HU",
    "Török": "HU",
    "Fehér": "HU",
    "Balázs": "HU",
    "Gál": "HU",
    "Blöndal": "IS",
    "Thorarensen": "IS",
    "Möller": "IS",
    "Waage": "IS",
    "Bergmann": "IS",
    "Briem": "IS",
    "Thorlacius": "IS",
    "Hjaltalín": "IS",
    "Scheving": "IS",
    "Kvaran": "IS",
    "Fjeldsted": "IS",
    "Norðdahl": "IS",
    "Berndsen": "IS",
    "Murphy": "AU",
    "Kelly": "AU",
    "O'Kelly": "IE",
    "Sullivan": "US",
    "O'Sullivan": "IE",
    "Walsh": "IE",
    "Smith": "NZ",
    "O'Brien": "IE",
    "Byrne": "IE",
    "O'Byrne": "IE",
    "O'Ryan": "IE",
    "Ryan": "AU",
    "O'Connor": "IE",
    "O'Neill": "IE",
    "Reilly": "IE",
    "O'Reilly": "IE",
    "Doyle": "IE",
    "McCarthy": "IE",
    "Gallagher": "IE",
    "O'Gallagher": "IE",
    "O'Doherty": "IE",
    "Doherty": "IE",
    "Kennedy": "IE",
    "Lynch": "IE",
    "Murray": "IE",
    "O'Quinn": "IE",
    "Quinn": "IE",
    "O'Moore": "IE",
    "Moore": "US",
    "Rossi": "AR",
    "Russo": "AR",
    "Ferrari": "AR",
    "Esposito": "IT",
    "Bianchi": "AR",
    "Romano": "AR",
    "Colombo": "AR",
    "Bruno": "AR",
    "Ricci": "IT",
    "Greco": "IT",
    "Marino": "AR",
    "Gallo": "AR",
    "De Luca": "IT",
    "Conti": "IT",
    "Costa": "BR",
    "Mancini": "IT",
    "Giordano": "IT",
    "Rizzo": "IT",
    "Lombardi": "IT",
    "Barbieri": "IT",
    "Moretti": "IT",
    "Fontana": "IT",
    "Caruso": "IT",
    "Mariani": "IT",
    "Ferrara": "IT",
    "Santoro": "IT",
    "Rinaldi": "IT",
    "Leone": "IT",
    "D'Angelo": "IT",
    "Longo": "IT",
    "Galli": "IT",
    "Martini": "IT",
    "Martinelli": "IT",
    "Serra": "IT",
    "Conte": "IT",
    "Vitale": "IT",
    "De Santis": "IT",
    "Marchetti": "IT",
    "Messina": "IT",
    "Gentile": "IT",
    "Villa": "IT",
    "Marini": "IT",
    "Lombardo": "IT",
    "Coppola": "IT",
    "Ferri": "IT",
    "Parisi": "IT",
    "De Angelis": "IT",
    "Bianco": "IT",
    "Amato": "IT",
    "Fabbri": "IT",
    "Gatti": "IT",
    "Sala": "IT",
    "Morelli": "IT",
    "Grasso": "IT",
    "Pellegrini": "IT",
    "Ferraro": "IT",
    "Monti": "IT",
    "Palumbo": "IT",
    "Grassi": "IT",
    "Testa": "IT",
    "Valentini": "IT",
    "Carbone": "IT",
    "Benedetti": "IT",
    "Silvestri": "IT",
    "Farina": "IT",
    "D'Amico": "IT",
    "Martino": "IT",
    "Bernardi": "IT",
    "Caputo": "IT",
    "Mazza": "IT",
    "Sanna": "IT",
    "Fiore": "IT",
    "De Rosa": "IT",
    "Pellegrino": "IT",
    "Giuliani": "IT",
    "Rizzi": "IT",
    "Di Stefano": "IT",
    "Cattaneo": "IT",
    "Rossetti": "IT",
    "Orlando": "IT",
    "Basile": "IT",
    "Neri": "IT",
    "Barone": "IT",
    "Palmieri": "IT",
    "Riva": "IT",
    "Romeo": "IT",
    "Franco": "PY",
    "Sorrentino": "IT",
    "Pagano": "IT",
    "D'Agostino": "IT",
    "Piras": "IT",
    "Ruggiero": "IT",
    "Montanari": "IT",
    "Battaglia": "IT",
    "Bellini": "IT",
    "Castelli": "IT",
    "Guerra": "IT",
    "Poli": "IT",
    "Valente": "IT",
    "Ferretti": "IT",
    "Morina": "XK",
    "Shala": "XK",
    "Bytyqi": "XK",
    "Kastrati": "XK",
    "Kryeziu": "XK",
    "Hoti": "XK",
    "Fatime": "XK",
    "Bajram": "XK",
    "Emine": "XK",
    "Bekim": "XK",
    "Afërdita": "XK",
    "Valon": "XK",
    "Egzon": "XK",
    "Arben": "XK",
    "Ramadan": "XK",
    "Muhamet": "XK",
    "Bērziņš": "LV",
    "Kalniņš": "LV",
    "Ozoliņš": "LV",
    "Jansons": "LV",
    "Ozols": "LV",
    "Liepiņš": "LV",
    "Krūmiņš": "LV",
    "Balodis": "LV",
    "Eglītis": "LV",
    "Zariņš": "LV",
    "Pētersons": "LV",
    "Vītols": "LV",
    "Kļaviņš": "LV",
    "Kārkliņš": "LV",
    "Vanags": "LV",
    "Kazlauskienė": "LT",
    "Kazlauskas": "LT",
    "Jankauskas": "LT",
    "Jankauskienė": "LT",
    "Petrauskas": "LT",
    "Petrauskienė": "LT",
    "Stankevičienė": "LT",
    "Stankevičius": "LT",
    "Vasiliauskas": "LT",
    "Vasiliauskienė": "LT",
    "Butkus": "LT",
    "Butkienė": "LT",
    "Žukauskienė": "LT",
    "Žukauskas": "LT",
    "Paulauskas": "LT",
    "Paulauskienė": "LT",
    "Urbonas": "LT",
    "Urbonienė": "LT",
    "Kavaliauskas": "LT",
    "Kavaliauskienė": "LT",
    "Schmit": "LU",
    "Muller": "LU",
    "Thill": "LU",
    "Schmitz": "BR",
    "Schroeder": "LU",
    "Reuter": "LU",
    "Kieffer": "LU",
    "Kremer": "LU",
    "Faber": "LU",
    "Weiss": "LU",
    "Schiltz": "LU",
    "Welter": "LU",
    "Majerus": "LU",
    "Ries": "LU",
    "Meyers": "LU",
    "Kayser": "LU",
    "Steffen": "LU",
    "Krier": "LU",
    "Braun": "LU",
    "Wagener": "LU",
    "Diederich": "LU",
    "Borg": "MT",
    "Camilleri": "MT",
    "Vella": "MT",
    "Farrugia": "MT",
    "Zammit": "MT",
    "Galea": "MT",
    "Micallef": "MT",
    "Grech": "MT",
    "Attard": "MT",
    "Spiteri": "MT",
    "Rusu": "RO",
    "Ceban": "MD",
    "Ciobanu": "RO",
    "Țurcan": "MD",
    "Cebotari": "MD",
    "Sîrbu": "MD",
    "Lungu": "MD",
    "Munteanu": "MD",
    "Rotari": "MD",
    "Popa": "RO",
    "Ursu": "MD",
    "Guțu": "MD",
    "Roșca": "MD",
    "Melnic": "MD",
    "Cojocari": "MD",
    "Vujović": "ME",
    "Radović": "ME",
    "Ivanović": "ME",
    "Radulović": "ME",
    "Perović": "ME",
    "De Jong": "NL",
    "Jansen": "NL",
    "De Vries": "NL",
    "Van den Berg": "NL",
    "Van Dijk": "NL",
    "Van Dyk": "NL",
    "Bakker": "NL",
    "Janssen": "NL",
    "Visser": "NL",
    "Smit": "NL",
    "Meijer": "NL",
    "De Boer": "NL",
    "Mulder": "NL",
    "De Groot": "NL",
    "Bos": "NL",
    "Vos": "NL",
    "Peters": "NL",
    "Hendriks": "NL",
    "Van Leeuwen": "NL",
    "Dekker": "NL",
    "Brouwer": "NL",
    "De Wit": "NL",
    "Dijkstra": "NL",
    "Smits": "NL",
    "De Graaf": "NL",
    "Van der Meer": "NL",
    "Andov": "MK",
    "Bozinov": "MK",
    "Brankov": "MK",
    "Damcevski": "MK",
    "Davidov": "MK",
    "Donev": "MK",
    "Filipov": "MK",
    "Ivanovski": "MK",
    "Janev": "MK",
    "Kitanovski": "MK",
    "Koloski": "MK",
    "Kostovski": "MK",
    "Kostov": "MK",
    "Manasievski": "MK",
    "Markov": "MK",
    "Markovski": "MK",
    "Markoski": "MK",
    "Matovski": "MK",
    "Mladenovski": "MK",
    "Nikolovski": "MK",
    "Pavlovski": "MK",
    "Penov": "MK",
    "Petkov": "MK",
    "Petrevski": "MK",
    "Petrovski": "MK",
    "Popoff": "MK",
    "Popovski": "MK",
    "Ristevski": "MK",
    "Stojanov": "MK",
    "Trajanoski": "MK",
    "Trajanovski": "MK",
    "Trajcevski": "MK",
    "Trajkovski": "MK",
    "Nilsen": "NO",
    "Kristiansen": "NO",
    "Karlsen": "NO",
    "Johnsen": "NO",
    "Pettersen": "NO",
    "Eriksen": "NO",
    "Berg": "NO",
    "Haugen": "NO",
    "Hagen": "NO",
    "Johannessen": "NO",
    "Andreassen": "NO",
    "Dahl": "NO",
    "Halvorsen": "NO",
    "Henriksen": "NO",
    "Lund": "NO",
    "Nowak": "PL",
    "Kowalski": "PL",
    "Wiśniewski": "PL",
    "Wójcik": "PL",
    "Kowalczyk": "PL",
    "Kamiński": "PL",
    "Lewandowski": "PL",
    "Zieliński": "PL",
    "Szymański": "PL",
    "Woźniak": "PL",
    "Dąbrowski": "PL",
    "Kozłowski": "PL",
    "Jankowski": "PL",
    "Mazur": "PL",
    "Kwiatkowski": "PL",
    "Wojciechowski": "PL",
    "Krawczyk": "PL",
    "Kaczmarek": "PL",
    "Piotrowski": "PL",
    "Grabowski": "PL",
    "Silva": "CL",
    "Ferreira": "BR",
    "Pereira": "BR",
    "Oliveira": "BR",
    "Rodrigues": "BR",
    "Martins": "BR",
    "Jesus": "PT",
    "Sousa": "BR",
    "Fernandes": "BR",
    "Gonçalves": "BR",
    "Gomes": "BR",
    "Lopes": "PT",
    "Marques": "PT",
    "Alves": "BR",
    "Almeida": "BR",
    "Ribeiro": "BR",
    "Pinto": "PT",
    "Carvalho": "BR",
    "Teixeira": "BR",
    "Moreira": "PT",
    "Correia": "BR",
    "Mendes": "PT",
    "Nunes": "PT",
    "Soares": "PT",
    "Vieira": "PT",
    "Monteiro": "PT",
    "Cardoso": "BR",
    "Rocha": "BR",
    "Neves": "PT",
    "Coelho": "PT",
    "Cunha": "PT",
    "Pires": "PT",
    "Duarte": "PY",
    "Reis": "PT",
    "Simões": "PT",
    "Antunes": "PT",
    "Matos": "PT",
    "Fonseca": "PT",
    "Machado": "PT",
    "Araújo": "BR",
    "Barbosa": "BR",
    "Tavares": "PT",
    "Lourenço": "PT",
    "Figueiredo": "PT",
    "Azevedo": "BR",
    "Freitas": "PT",
    "Popescu": "RO",
    "Pop": "RO",
    "Radu": "RO",
    "Dumitru": "RO",
    "Stan": "RO",
    "Stoica": "RO",
    "Gheorghe": "RO",
    "Matei": "RO",
    "Ionescu": "RO",
    "Đorđević": "RS",
    "Stojanović": "RS",
    "Stanković": "RS",
    "Milošević": "RS",
    "Kováč": "SK",
    "Baláž": "SK",
    "Balog": "SK",
    "Lukáč": "SK",
    "Polák": "SK",
    "Gajdoš": "SK",
    "Kollár": "SK",
    "Hudák": "SK",
    "Neméth": "SK",
    "Kováčik": "SK",
    "Oravec": "SK",
    "Kovačič": "SI",
    "Krajnc": "SI",
    "Zupančič": "SI",
    "Potočnik": "SI",
    "Mlakar": "SI",
    "Kos": "SI",
    "Vidmar": "SI",
    "Golob": "SI",
    "Turk": "SI",
    "Božič": "SI",
    "Kralj": "SI",
    "Korošec": "SI",
    "Zupan": "SI",
    "Bizjak": "SI",
    "Hribar": "SI",
    "Kotnik": "SI",
    "Kavčič": "SI",
    "Rozman": "SI",
    "Kastelic": "SI",
    "Oblak": "SI",
    "Žagar": "SI",
    "Petek": "SI",
    "Hočevar": "SI",
    "Kolar": "SI",
    "Košir": "SI",
    "Koren": "SI",
    "Klemenčič": "SI",
    "García": "PE",
    "Fernández": "PE",
    "González": "PE",
    "Rodríguez": "PE",
    "López": "PE",
    "Martínez": "PE",
    "Sánchez": "PE",
    "Pérez": "PE",
    "Martín": "AR",
    "Gómez": "PY",
    "Ruiz": "PY",
    "Hernández": "CO",
    "Jiménez": "CO",
    "Díaz": "PE",
    "Álvarez": "CL",
    "Moreno": "CO",
    "Muñoz": "CO",
    "Alonso": "AR",
    "Gutiérrez": "PE",
    "Romero": "PE",
    "Domínguez": "AR",
    "Gil": "AR",
    "Vázquez": "ES",
    "Serrano": "MX",
    "Blanco": "AR",
    "Sanz": "ES",
    "Suárez": "AR",
    "Ortega": "CL",
    "Rubio": "ES",
    "Molina": "CL",
    "Delgado": "AR",
    "Ramírez": "PE",
    "Ortiz": "PY",
    "Marín": "ES",
    "Iglesias": "AR",
    "Vásquez": "PE",
    "Mejía": "MX",
    "Rivas": "AR",
    "Portillo": "SV",
    "Escobar": "CL",
    "Orellana": "CL",
    "Alvarado": "CL",
    "Meier": "CH",
    "Keller": "CH",
    "Baumann": "CH",
    "Gerber": "CH",
    "Frei": "CH",
    "Melnyk": "UA",
    "Shevchenko": "UA",
    "Boyko": "UA",
    "Kovalenko": "UA",
    "Tkachenko": "UA",
    "Kovalchuk": "UA",
    "Kravchenko": "UA",
    "Yakovenko": "UA",
    "Shevchuk": "UA",
    "Koval": "UA",
    "Polishchuk": "UA",
    "Bondar": "UA",
    "Tkachuk": "UA",
    "Moroz": "UA",
    "Marchenko": "UA",
    "Lysenko": "UA",
    "Rudenko": "UA",
    "Savchenko": "UA",
    "Petrenko": "UA",
    "Brown": "NZ",
    "Jones": "NZ",
    "Williams": "NZ",
    "Johnson": "AU",
    "Taylor": "NZ",
    "Roberts": "US",
    "Khan": "FJ",
    "Lewis": "US",
    "Jackson": "US",
    "Clarke": "GB",
    "James": "US",
    "Phillips": "US",
    "Wilson": "NZ",
    "Mason": "GB",
    "Mitchell": "US",
    "Rose": "GB",
    "Davis": "US",
    "Davies": "GB",
    "Cox": "US",
    "Alexander": "GB",
    "Tremblay": "CA",
    "Roy": "CA",
    "Gagnon": "CA",
    "MacDonald": "CA",
    "Mora": "CR",
    "Calderón": "CR",
    "Rojas": "PE",
    "Vargas": "PE",
    "Salas": "CR",
    "Segura": "CR",
    "Valverde": "CR",
    "Villalobos": "CR",
    "Araya": "CL",
    "Herrera": "PY",
    "Madrigal": "CR",
    "Peña": "CL",
    "Rosario": "DO",
    "Santana": "DO",
    "Núñez": "PY",
    "de la Cruz": "DO",
    "Guzmán": "CL",
    "Fuentes": "CL",
    "De Los Santos": "DO",
    "Ponce": "AR",
    "Montes": "BR",
    "De León": "GT",
    "Estrada": "MX",
    "Marroquín": "GT",
    "Méndez": "AR",
    "Velásquez": "MX",
    "Ruíz": "PE",
    "Ortíz": "MX",
    "Chávez": "PE",
    "Medina": "CL",
    "Juárez": "AR",
    "Salazar": "PE",
    "Guerrero": "CL",
    "Contreras": "CL",
    "Luna": "AR",
    "Garza": "MX",
    "Soto": "CL",
    "Cortez": "MX",
    "Lara": "MX",
    "Espinoza": "PE",
    "Vega": "CL",
    "Ávila": "MX",
    "Cervantes": "MX",
    "Sandoval": "CL",
    "Carrillo": "MX",
    "León": "MX",
    "Ríos": "AR",
    "Márquez": "MX",
    "Campos": "CL",
    "Ibarra": "MX",
    "Solís": "MX",
    "Rosas": "MX",
    "Camacho": "MX",
    "Cárdenas": "CL",
    "Orozco": "MX",
    "Aguirre": "AR",
    "Acosta": "PY",
    "Padilla": "MX",
    "Robles": "MX",
    "Cabrera": "AR",
    "Rosales": "MX",
    "Pacheco": "MX",
    "Castañeda": "MX",
    "Valenzuela": "CL",
    "Rangel": "MX",
    "Ayala": "PY",
    "Meza": "MX",
    "Nava": "MX",
    "Valencia": "MX",
    "Maldonado": "CL",
    "Ochoa": "MX",
    "Tapia": "CL",
    "Salinas": "CL",
    "Zamora": "MX",
    "Miller": "US",
    "Anderson": "AU",
    "Thompson": "AU",
    "White": "AU",
    "Gonzalez": "US",
    "Harris": "AU",
    "Clark": "US",
    "Robinson": "AU",
    "Walker": "AU",
    "Hall": "US",
    "Allen": "US",
    "Wright": "US",
    "King": "US",
    "Scott": "US",
    "Green": "US",
    "Baker": "US",
    "Adams": "US",
    "Nelson": "US",
    "Hill": "US",
    "Campbell": "US",
    "Carter": "US",
    "Evans": "US",
    "Turner": "AU",
    "Parker": "US",
    "Collins": "US",
    "Edwards": "US",
    "Stewart": "US",
    "Morris": "US",
    "Cook": "US",
    "Rogers": "US",
    "Morgan": "US",
    "Peterson": "US",
    "Cooper": "US",
    "Reed": "US",
    "Bailey": "US",
    "Bell": "US",
    "Howard": "US",
    "Ward": "US",
    "Richardson": "US",
    "Wood": "US",
    "Watson": "US",
    "Brooks": "US",
    "Bennett": "US",
    "Gray": "US",
    "Hughes": "US",
    "Price": "US",
    "Myers": "US",
    "Foster": "US",
    "Sanders": "US",
    "Ross": "US",
    "Powell": "US",
    "Russell": "US",
    "Jenkins": "US",
    "Perry": "US",
    "Butler": "US",
    "Barnes": "US",
    "Fisher": "US",
    "Prasad": "FJ",
    "Chand": "FJ",
    "Lal": "FJ",
    "Narayan": "FJ",
    "Ram": "FJ",
    "Naidu": "FJ",
    "Chandra": "FJ",
    "Nand": "FJ",
    "Lata": "FJ",
    "Deo": "FJ",
    "Reddy": "FJ",
    "Prakash": "FJ",
    "Raj": "FJ",
    "Maharaj": "FJ",
    "Waqa": "FJ",
    "Goundar": "FJ",
    "Kaur": "NZ",
    "Sosa": "AR",
    "Giménez": "PY",
    "Varela": "AR",
    "Pereyra": "AR",
    "Benítez": "PY",
    "Arias": "AR",
    "Otero": "AR",
    "Rey": "AR",
    "Vidal": "CL",
    "Paz": "AR",
    "Correa": "BR",
    "Ferreyra": "AR",
    "Quiroga": "AR",
    "Vera": "PY",
    "Lorenzo": "AR",
    "Godoy": "CL",
    "Rivero": "AR",
    "Peralta": "AR",
    "Figueroa": "CL",
    "Calvo": "AR",
    "Ibáñez": "AR",
    "Cáceres": "PY",
    "Carrizo": "AR",
    "Ledesma": "AR",
    "Soria": "AR",
    "Villalba": "PY",
    "Prieto": "AR",
    "Lima": "BR",
    "Melo": "BR",
    "Cavalcante": "BR",
    "Cavalcanti": "BR",
    "Morais": "BR",
    "Sepúlveda": "CL",
    "Carrasco": "CL",
    "Cortés": "CL",
    "Jara": "CL",
    "Vergara": "CL",
    "Riquelme": "CL",
    "Bravo": "CL",
    "Zúñiga": "CL",
    "Olivares": "CL",
    "Alarcón": "CL",
    "Gallardo": "CL",
    "Garrido": "CL",
    "Henríquez": "CL",
    "Saavedra": "CL",
    "Aguilera": "CL",
    "Parra": "CL",
    "Aravena": "CL",
    "Pizarro": "CL",
    "Leiva": "CL",
    "Yáñez": "CL",
    "Valdés": "CL",
    "Lagos": "CL",
    "Bustos": "CL",
    "Pino": "CL",
    "Palma": "CL",
    "Sanhueza": "CL",
    "Carvajal": "CL",
    "Navarrete": "CL",
    "Sáez": "CL",
    "Donoso": "CL",
    "Poblete": "CL",
    "Bustamante": "CL",
    "Toro": "CL",
    "Venegas": "CL",
    "Paredes": "CL",
    "Farías": "CL",
    "San Martín": "CL",
    "Báez": "PY",
    "Galeano": "PY",
    "Cardozo": "PY",
    "Quispe": "PE",
    "Huamán": "PE",
    "Mamani": "PE",
    "Pinas": "SR",
    "Mohan": "SR",
    "Kalloe": "SR",
    "Lie": "SR",
    "van Dijk": "SR",
    "Tjin": "SR",
    "Kluivert": "SR",
    "Semil": "SR",
    "Sabajo": "SR"
};
var LNkeys = Object.keys(lastNames);

var countries = {
    "AF": "Afghanistan",
    "AX": "Aland Islands",
    "AL": "Albania",
    "DZ": "Algeria",
    "AS": "American Samoa",
    "AD": "Andorra",
    "AO": "Angola",
    "AI": "Anguilla",
    "AQ": "Antarctica",
    "AG": "Antigua And Barbuda",
    "AR": "Argentina",
    "AM": "Armenia",
    "AW": "Aruba",
    "AU": "Australia",
    "AT": "Austria",
    "AZ": "Azerbaijan",
    "BS": "Bahamas",
    "BH": "Bahrain",
    "BD": "Bangladesh",
    "BB": "Barbados",
    "BY": "Belarus",
    "BE": "Belgium",
    "BZ": "Belize",
    "BJ": "Benin",
    "BM": "Bermuda",
    "BT": "Bhutan",
    "BO": "Bolivia",
    "BA": "Bosnia And Herzegovina",
    "BW": "Botswana",
    "BV": "Bouvet Island",
    "BR": "Brazil",
    "IO": "British Indian Ocean Territory",
    "BN": "Brunei Darussalam",
    "BG": "Bulgaria",
    "BF": "Burkina Faso",
    "BI": "Burundi",
    "KH": "Cambodia",
    "CM": "Cameroon",
    "CA": "Canada",
    "CV": "Cape Verde",
    "KY": "Cayman Islands",
    "CF": "Central African Republic",
    "TD": "Chad",
    "CL": "Chile",
    "CN": "China",
    "CX": "Christmas Island",
    "CC": "Cocos (Keeling) Islands",
    "CO": "Colombia",
    "KM": "Comoros",
    "CG": "Congo",
    "CD": "Congo, Democratic Republic",
    "CK": "Cook Islands",
    "CR": "Costa Rica",
    "CI": "Cote D\"Ivoire",
    "HR": "Croatia",
    "CU": "Cuba",
    "CY": "Cyprus",
    "CZ": "Czech Republic",
    "DK": "Denmark",
    "DJ": "Djibouti",
    "DM": "Dominica",
    "DO": "Dominican Republic",
    "EC": "Ecuador",
    "EG": "Egypt",
    "SV": "El Salvador",
    "GQ": "Equatorial Guinea",
    "ER": "Eritrea",
    "EE": "Estonia",
    "ET": "Ethiopia",
    "FK": "Falkland Islands (Malvinas)",
    "FO": "Faroe Islands",
    "FJ": "Fiji",
    "FI": "Finland",
    "FR": "France",
    "GF": "French Guiana",
    "PF": "French Polynesia",
    "TF": "French Southern Territories",
    "GA": "Gabon",
    "GM": "Gambia",
    "GE": "Georgia",
    "DE": "Germany",
    "GH": "Ghana",
    "GI": "Gibraltar",
    "GR": "Greece",
    "GL": "Greenland",
    "GD": "Grenada",
    "GP": "Guadeloupe",
    "GU": "Guam",
    "GT": "Guatemala",
    "GG": "Guernsey",
    "GN": "Guinea",
    "GW": "Guinea-Bissau",
    "GY": "Guyana",
    "HT": "Haiti",
    "HM": "Heard Island & Mcdonald Islands",
    "VA": "Holy See (Vatican City State)",
    "HN": "Honduras",
    "HK": "Hong Kong",
    "HU": "Hungary",
    "IS": "Iceland",
    "IN": "India",
    "ID": "Indonesia",
    "IR": "Iran, Islamic Republic Of",
    "IQ": "Iraq",
    "IE": "Ireland",
    "IM": "Isle Of Man",
    "IL": "Israel",
    "IT": "Italy",
    "JM": "Jamaica",
    "JP": "Japan",
    "JE": "Jersey",
    "JO": "Jordan",
    "KZ": "Kazakhstan",
    "KE": "Kenya",
    "KI": "Kiribati",
    "KR": "Korea",
    "KP": "North Korea",
    "KW": "Kuwait",
    "KG": "Kyrgyzstan",
    "LA": "Lao People\"s Democratic Republic",
    "LV": "Latvia",
    "LB": "Lebanon",
    "LS": "Lesotho",
    "LR": "Liberia",
    "LY": "Libyan Arab Jamahiriya",
    "LI": "Liechtenstein",
    "LT": "Lithuania",
    "LU": "Luxembourg",
    "MO": "Macao",
    "MK": "Macedonia",
    "MG": "Madagascar",
    "MW": "Malawi",
    "MY": "Malaysia",
    "MV": "Maldives",
    "ML": "Mali",
    "MT": "Malta",
    "MH": "Marshall Islands",
    "MQ": "Martinique",
    "MR": "Mauritania",
    "MU": "Mauritius",
    "YT": "Mayotte",
    "MX": "Mexico",
    "FM": "Micronesia, Federated States Of",
    "MD": "Moldova",
    "MC": "Monaco",
    "MN": "Mongolia",
    "ME": "Montenegro",
    "MS": "Montserrat",
    "MA": "Morocco",
    "MZ": "Mozambique",
    "MM": "Myanmar",
    "NA": "Namibia",
    "NR": "Nauru",
    "NP": "Nepal",
    "NL": "Netherlands",
    "AN": "Netherlands Antilles",
    "NC": "New Caledonia",
    "NZ": "New Zealand",
    "NI": "Nicaragua",
    "NE": "Niger",
    "NG": "Nigeria",
    "NU": "Niue",
    "NF": "Norfolk Island",
    "MP": "Northern Mariana Islands",
    "NO": "Norway",
    "OM": "Oman",
    "PK": "Pakistan",
    "PW": "Palau",
    "PS": "Palestinian Territory, Occupied",
    "PA": "Panama",
    "PG": "Papua New Guinea",
    "PY": "Paraguay",
    "PE": "Peru",
    "PH": "Philippines",
    "PN": "Pitcairn",
    "PL": "Poland",
    "PT": "Portugal",
    "PR": "Puerto Rico",
    "QA": "Qatar",
    "RE": "Reunion",
    "RO": "Romania",
    "RU": "Russian Federation",
    "RW": "Rwanda",
    "BL": "Saint Barthelemy",
    "SH": "Saint Helena",
    "KN": "Saint Kitts And Nevis",
    "LC": "Saint Lucia",
    "MF": "Saint Martin",
    "PM": "Saint Pierre And Miquelon",
    "VC": "Saint Vincent And Grenadines",
    "WS": "Samoa",
    "SM": "San Marino",
    "ST": "Sao Tome And Principe",
    "SA": "Saudi Arabia",
    "SN": "Senegal",
    "RS": "Serbia",
    "SC": "Seychelles",
    "SL": "Sierra Leone",
    "SG": "Singapore",
    "SK": "Slovakia",
    "SI": "Slovenia",
    "SB": "Solomon Islands",
    "SO": "Somalia",
    "ZA": "South Africa",
    "GS": "South Georgia And Sandwich Isl.",
    "ES": "Spain",
    "LK": "Sri Lanka",
    "SD": "Sudan",
    "SR": "Suriname",
    "SJ": "Svalbard And Jan Mayen",
    "SZ": "Swaziland",
    "SE": "Sweden",
    "CH": "Switzerland",
    "SY": "Syrian Arab Republic",
    "TW": "Taiwan",
    "TJ": "Tajikistan",
    "TZ": "Tanzania",
    "TH": "Thailand",
    "TL": "Timor-Leste",
    "TG": "Togo",
    "TK": "Tokelau",
    "TO": "Tonga",
    "TT": "Trinidad And Tobago",
    "TN": "Tunisia",
    "TR": "Turkey",
    "TM": "Turkmenistan",
    "TC": "Turks And Caicos Islands",
    "TV": "Tuvalu",
    "UG": "Uganda",
    "UA": "Ukraine",
    "AE": "United Arab Emirates",
    "GB": "United Kingdom",
    "US": "United States",
    "UM": "United States Outlying Islands",
    "UY": "Uruguay",
    "UZ": "Uzbekistan",
    "VU": "Vanuatu",
    "VE": "Venezuela",
    "VN": "Vietnam",
    "VG": "Virgin Islands, British",
    "VI": "Virgin Islands, U.S.",
    "WF": "Wallis And Futuna",
    "EH": "Western Sahara",
    "YE": "Yemen",
    "ZM": "Zambia",
    "ZW": "Zimbabwe"
};

var getAge = function () {
    var group = 8 * Math.random();
    if (group < 0.8) {
        return Math.floor(65 + 35 * Math.random());
    } else if (group < 4.7) {
        return Math.floor(25 + 40 * Math.random());
    } else if (group < 5.9) {
        return Math.floor(15 + 10 * Math.random());
    } else if (group < 7.3) {
        return Math.floor(5 + 10 * Math.random());
    } else {
        return Math.floor(5 * Math.random());
    }
}

var cods = [
    'starved because of low supplies',
    'assassinated in a territorial war',
    'died from an infection',
    'died from overheating in a desertic region',
    'was asphyxiated in a humid climate',
    'drowned in a flood',
    'was crushed by collapsing infrastructure',
    'suffocated in a wildfire',
    'died in a hurricane',
    'froze to death during a severe winter storm',
    'died of dehydration during a drought',
    'poisoned by contaminated water',
    'starved due to crop failures',
    'died from heatstroke during a heatwave',
    'was killed in a riot over scarce resources',
    'died of a respiratory illness from pollution',
    'was killed in a landslide',
    'swept away by a tsunami',
    'died of hypothermia in an unseasonal cold snap',
    'suffered a heart attack during a heatwave',
    'died of malnutrition in a famine',
    'was killed in a conflict over water rights',
    'died from an untreated illness due to healthcare collapse',
    'caught in an avalanche',
    'died of complications from a mosquito-borne disease',
    'suffered a stroke due to extreme heat',
    'died of a waterborne disease after flooding',
    'trampled in a stampede during an evacuation',
    'died of smoke inhalation during a wildfire',
    'was killed in a traffic accident during a mass evacuation',
    'died of carbon monoxide poisoning from heating indoors',
    'starved after fisheries collapsed',
    'died from exposure in extreme weather conditions',
    'committed suicide',
    'died in a wildfire while trying to evacuate',
    'died of thirst in an arid region',
    'died from drinking contaminated water post-disaster',
    'died of cholera in the aftermath of a flood',
    'was killed in an outbreak of violence over food supplies',
    'suffered fatal injuries in an urban heat island effect',
    'died of a neglected chronic illness as health systems fail',
    'perished in a mudslide',
    'died from extreme weather exacerbating existing health conditions',
    'died of hypoxia due to air quality degradation',
    'perished in an industrial accident during a climate disaster',
    'died of cardiovascular complications during a heatwave',
    'was killed in a violent dispute over grazing land',
    'died of severe dehydration after being stranded during a climate event',
    'died in a forest fire',
    'died of food poisoning from spoiled supplies in a blackout',
    'was killed in an accident while trying to migrate to a safer area',
    'was killed in a fight over dwindling food supplies',
    'died in a protest against government inaction',
    'assaulted and left to die during civil unrest',
    'died from neglect in an overcrowded refugee camp',
    'murdered for access to clean water',
    'died homeless after a climate disaster',
    'was killed in a dispute over property lines after flooding',
    'lynched in a scapegoating incident',
    'died from untreated injuries in a collapsed healthcare system',
    'was killed in a mass panic during a disaster evacuation',
    'died in a labor strike violently repressed',
    'murdered in a conflict over fertile land',
    'died in an armed robbery for scarce resources',
    'suffered fatal injuries in a riot over economic collapse',
    'died in a shelter fire due to overcrowding',
    'was killed in a conflict over fishing rights',
    'died in a stampede for emergency supplies',
    'was killed in a territorial gang war over resource-rich areas',
    'died from lack of medical care during societal breakdown',
    'assassinated for political reasons',
    'died in a brawl over rationed goods',
    'perished in human trafficking during mass migrations',
    'was killed in a land dispute turned violent',
    'died in a vigilante attack due to resource hoarding',
    'died from domestic violence',
    'was killed in an uprising against corrupt authorities',
    'died in a communal clash over water distribution',
    'murdered in a feud over deforested land',
    'died from police brutality during a protest',
    'died in a workplace accident due to unsafe conditions under climate stress',
    'died of starvation after being ostracized from community resources',
    'was killed in a conflict over energy resources',
    'died from overexertion in forced labor camps',
    'was killed in a dispute over livestock ownership after droughts',
    'died in an arson attack related to land conflicts',
    'died from lack of social support in post-disaster chaos',
    'was killed in a border conflict',
    'died in a hate crime',
    'died from exploitation and unsafe working conditions in disaster recovery efforts',
    'was killed in a sabotage incident',
    'died in a plane crash due to erratic weather patterns',
    'was killed in a train derailment caused by extreme heat warping tracks',
    'died from food poisoning due to disrupted supply chains',
    'died from a venomous insect bite',
    'died in an elevator malfunction during a heatwave power outage',
    'died from carbon monoxide poisoning from makeshift heating',
    'was killed in a robbery as economic conditions worsened',
    'died in a stampede at a food distribution center',
    'died in a building collapse due to ground subsidence',
    'died of an untreated infection as antibiotics became scarce',
    'died in a fight over diminishing fisheries',
    'died in a car crash during a blackout when traffic lights failed',
    'died in a mine collapse exacerbated by heavy rains',
    'died from drinking counterfeit bottled water',
    'died from a fall in a poorly maintained building',
    'died from an asthma attack during high pollution days',
    'died in a boating accident in a flooded urban area',
    'died in a hunting accident as wildlife patterns shifted',
    'died from a septicemia due to untreated wound infections',
    'died in a forest collapse caused by pest infestations',
    'died from radiation exposure due to damaged infrastructure',
    'died in an explosion from a ruptured gas line in a flood',
    'died from a brain aneurysm during extreme stress events',
    'died in a landslide caused by deforestation',
    'died from hypothermia in an unexpected cold snap after displacement',
    'died from a building fire in an overpopulated area',
    'died from a stroke triggered by prolonged heat exposure',
    'died from an untreated dental infection',
    'died from an overdose',
    'died from exposure to toxic waste in improperly managed landfills',
    'died during a forced eviction',
    'died in a bridge collapse',
    'died in a house fire from using unsafe heating methods',
    'died from a waterborne disease in makeshift housing',
    'died in a gas explosion from compromised infrastructure',
    'died in a traffic accident during an emergency evacuation',
    'died in a scaffolding collapse in a hurried construction',
    'died from anaphylactic shock due to new allergens in the environment',
    'died from complications of diabetes in disrupted medical services',
    'died from a severe infection as healthcare systems overwhelmed',
    'was beaten up in a conflict over resources',
    'suffocated in a poorly ventilated shelter',
    'was trapped in an elevator during a blackout',
    'was overwhelmed by smoke in a wildfire',
    'was swept away in a flash flood',
    'was caught in a stampede for food supplies',
    'was poisoned by toxic algae blooms in drinking water',
    'was electrocuted by downed power lines in a storm',
    'was buried under a landslide caused by deforestation',
    'was stung by invasive insects with severe allergic reaction',
    'was infected by a new mosquito-borne disease',
    'was caught in a crossfire during resource conflicts',
    'was crushed by collapsing infrastructure in an earthquake',
    'was starved after crop failures led to famine',
    'was left untreated due to hospital overcrowding',
    'was dehydrated in an extended drought',
    'was asphyxiated in a dust storm',
    'was lynched in a climate migration dispute',
    'was assaulted during a riot for scarce supplies',
    'was frozen in an unexpected cold snap',
    'was suffocated by air pollution in a heatwave',
    'was abandoned in an overcrowded refugee camp',
    'was beaten in a conflict over fertile land',
    'was crushed by a tree during a hurricane',
    'was killed in a riot over water access',
    'was stranded and dehydrated in a desertified area',
    'was poisoned by contaminated fish in warming oceans',
    'died from malaria',
    'succumbed to dengue fever',
    'perished from heatstroke',
    'died from dehydration',
    'suffocated from respiratory diseases worsened by air pollution',
    'died from cholera',
    'perished from typhoid fever',
    'died from encephalitis caused by vector-borne diseases',
    'succumbed to Lyme disease',
    'died from malnutrition',
    'died from cardiovascular disease',
    'perished from tuberculosis',
    'died from asthma complications',
    'succumbed to heat-related kidney failure',
    'died from complications of diabetes',
    'died from leptospirosis',
    'succumbed to meningitis outbreaks',
    'died from yellow fever',
    'died from a new strain of SARS',
    'died from neglected tropical diseases',
    'died from diarrheal diseases due to contaminated water sources',
    'perished from hepatitis outbreaks',
    'died from skin infections',
    'died from sepsis due to infections from wounds sustained during natural disasters',
    'succumbed to acute kidney injury from dehydration during droughts',
    'succumbed to respiratory infections',
    'died from schistosomiasis',
    'died from complications of sickle cell disease',
    'died from complications of chronic obstructive pulmonary disease',
    'perished from hepatitis outbreaks',
    'died from skin infections',
    'died from dyssentery',
    'died from sepsis due to infections from wounds sustained during natural disasters',
    'succumbed to acute kidney injury from dehydration during droughts',
];

var hobbies = [
    "3D printing",
    "Acrobatics",
    "Acting",
    "Amateur radio",
    "Animation",
    "Aquascaping",
    "Astrology",
    "Astronomy",
    "Baking",
    "Baton twirling",
    "Blogging",
    "Building",
    "Board/tabletop games",
    "Book discussion clubs",
    "Book restoration",
    "Bowling",
    "Brazilian jiu-jitsu",
    "Breadmaking",
    "Bullet journaling",
    "Cabaret",
    "Calligraphy",
    "Candle making",
    "Candy making",
    "Car fixing & building",
    "Card games",
    "Cheesemaking",
    "Cleaning",
    "Clothesmaking",
    "Coffee roasting",
    "Collecting",
    "Coloring",
    "Computer programming",
    "Confectionery",
    "Cooking",
    "Cosplaying",
    "Couponing",
    "Craft",
    "Creative writing",
    "Crocheting",
    "Cross-stitch",
    "Crossword puzzles",
    "Cryptography",
    "Cue sports",
    "Dance",
    "Digital arts",
    "Distro Hopping",
    "DJing",
    "Do it yourself",
    "Drama",
    "Drawing",
    "Drink mixing",
    "Drinking",
    "Electronic games",
    "Electronics",
    "Embroidery",
    "Experimenting",
    "Fantasy sports",
    "Fashion",
    "Fashion design",
    "Fishkeeping",
    "Filmmaking",
    "Flower arranging",
    "Fly tying",
    "Foreign language learning",
    "Furniture building",
    "Gaming",
    "Genealogy",
    "Gingerbread house making",
    "Glassblowing",
    "Graphic design",
    "Gunsmithing",
    "Gymnastics",
    "Hacking",
    "Herp keeping",
    "Home improvement",
    "Homebrewing",
    "Houseplant care",
    "Hula hooping",
    "Humor",
    "Hydroponics",
    "Ice skating",
    "Jewelry making",
    "Jigsaw puzzles",
    "Journaling",
    "Juggling",
    "Karaoke",
    "Karate",
    "Kendama",
    "Knife making",
    "Knitting",
    "Knot tying",
    "Kombucha brewing",
    "Lace making",
    "Lapidary",
    "Leather crafting",
    "Lego building",
    "Lock picking",
    "Listening to music",
    "Listening to podcasts",
    "Machining",
    "Macrame",
    "Magic",
    "Makeup",
    "Mazes (indoor/outdoor)",
    "Metalworking",
    "Model building",
    "Model engineering",
    "Nail art",
    "Needlepoint",
    "Origami",
    "Painting",
    "Palmistry",
    "Pet adoption & fostering",
    "Philately",
    "Photography",
    "Practical jokes",
    "Pressed flower craft",
    "Playing musical instruments",
    "Poi",
    "Pottery",
    "Powerlifting",
    "Puzzles",
    "Quilling",
    "Quilting",
    "Quizzes",
    "Radio-controlled model",
    "Rail transport modeling",
    "Rapping",
    "Reading",
    "Refinishing",
    "Reiki",
    "Robot combat",
    "Rubik's Cube",
    "Scrapbooking",
    "Sculpting",
    "Sewing",
    "Shoemaking",
    "Singing",
    "Sketching",
    "Skipping rope",
    "Slot car",
    "Soapmaking",
    "Social media",
    "Spreadsheets",
    "Stand-up comedy",
    "Stamp collecting",
    "Table tennis",
    "Tarot",
    "Taxidermy",
    "Thrifting",
    "Video editing",
    "Video game developing",
    "Video gaming",
    "Watching movies",
    "Watching television",
    "Videography",
    "Virtual reality",
    "Waxing",
    "Weaving",
    "Weight training",
    "Welding",
    "Whittling",
    "Wikipedia editing",
    "Winemaking",
    "Wood carving",
    "Woodworking",
    "Worldbuilding",
    "Writing",
    "Word searches",
    "Yo-yoing",
    "Yoga",
    "Zumba",
    "Amusement park visiting",
    "Air sports",
    "Airsoft",
    "Amateur geology",
    "Archery",
    "Astronomy",
    "Backpacking",
    "Badminton",
    "BASE jumping",
    "Baseball",
    "Basketball",
    "Beekeeping",
    "Birdwatching",
    "Blacksmithing",
    "BMX",
    "Board sports",
    "Bodybuilding",
    "Bonsai",
    "Butterfly watching",
    "Bus riding",
    "Camping",
    "Canoeing",
    "Canyoning",
    "Car riding",
    "Caving",
    "Composting",
    "Cycling",
    "Dowsing",
    "Driving",
    "Farming",
    "Fishing",
    "Flag football",
    "Flower growing",
    "Flying",
    "Flying disc",
    "Foraging",
    "Fossicking",
    "Freestyle football",
    "Gardening",
    "Geocaching",
    "Ghost hunting",
    "Gold prospecting",
    "Graffiti",
    "Handball",
    "Herbalism",
    "Herping",
    "High-power rocketry",
    "Hiking",
    "Hobby horsing",
    "Hobby tunneling",
    "Hooping",
    "Horseback riding",
    "Hunting",
    "Inline skating",
    "Jogging",
    "Jumping rope",
    "Kayaking",
    "Kite flying",
    "Kitesurfing",
    "Lacrosse",
    "LARPing",
    "Letterboxing",
    "Longboarding",
    "Martial arts",
    "Metal detecting",
    "Meteorology",
    "Motor sports",
    "Mountain biking",
    "Mountaineering",
    "Museum visiting",
    "Mushroom hunting",
    "Netball",
    "Nordic skating",
    "Orienteering",
    "Paintball",
    "Parkour",
    "Photography",
    "Podcast hosting",
    "Polo",
    "Public transport riding",
    "Rafting",
    "Railway journeys",
    "Rappelling",
    "Road biking",
    "Rock climbing",
    "Roller skating",
    "Rugby",
    "Running",
    "Radio-controlled model",
    "Sailing",
    "Sand art",
    "Scouting",
    "Scuba diving",
    "Sculling",
    "Shooting",
    "Shopping",
    "Shuffleboard",
    "Skateboarding",
    "Skiing",
    "Skimboarding",
    "Skydiving",
    "Slacklining",
    "Snowboarding",
    "Snowmobiling",
    "Snowshoeing",
    "Soccer",
    "Stone skipping",
    "Sun bathing",
    "Surfing",
    "Survivalism",
    "Swimming",
    "Taekwondo",
    "Tai chi",
    "Tennis",
    "Topiary",
    "Tourism",
    "Thru-hiking",
    "Trade fair visiting",
    "Travel",
    "Urban exploration",
    "Vacation",
    "Vegetable farming",
    "Videography",
    "Vehicle restoration",
    "Walking",
    "Water sports",
    "Astronomy",
    "Biology",
    "Chemistry",
    "Electrochemistry",
    "Physics",
    "Psychology",
    "Sports science",
    "Geography",
    "History",
    "Mathematics",
    "Railway studies",
    "Action figure",
    "Antiquing",
    "Ant-keeping",
    "Art collecting",
    "Book collecting",
    "Button collecting",
    "Cartophily",
    "Coin collecting",
    "Comic book collecting",
    "Deltiology",
    "Die-cast toy",
    "Digital hoarding",
    "Dolls",
    "Element collecting",
    "Ephemera collecting",
    "Fusilately",
    "Knife collecting",
    "Lotology",
    "Movie and movie memorabilia collecting",
    "Fingerprint collecting",
    "Perfume",
    "Phillumeny",
    "Radio-controlled model",
    "Rail transport modelling",
    "Record collecting",
    "Rock tumbling",
    "Scutelliphily",
    "Shoes",
    "Slot car",
    "Sports memorabilia",
    "Stamp collecting",
    "Stuffed toy collecting",
    "Tea bag collecting",
    "Ticket collecting",
    "Toys",
    "Transit map collecting",
    "Video game collecting",
    "Vintage cars",
    "Vintage clothing",
    "Vinyl Records",
    "Antiquities",
    "Auto audiophilia",
    "Flower collecting and pressing",
    "Fossil hunting",
    "Insect collecting",
    "Magnet fishing",
    "Metal detecting",
    "Mineral collecting",
    "Rock balancing",
    "Sea glass collecting",
    "Seashell collecting",
    "Stone collecting",
    "Animal fancy",
    "Axe throwing",
    "Backgammon",
    "Badminton",
    "Baton twirling",
    "Beauty pageants",
    "Billiards",
    "Bowling",
    "Boxing",
    "Bridge",
    "Checkers (draughts)",
    "Cheerleading",
    "Chess",
    "Color guard",
    "Cribbage",
    "Curling",
    "Dancing",
    "Darts",
    "Debate",
    "Dominoes",
    "Eating",
    "Esports",
    "Fencing",
    "Go",
    "Gymnastics",
    "Ice hockey",
    "Ice skating",
    "Judo",
    "Jujitsu",
    "Kabaddi",
    "Knowledge/word games",
    "Laser tag",
    "Longboarding",
    "Mahjong",
    "Marbles",
    "Martial arts",
    "Model United Nations",
    "Poker",
    "Pool",
    "Role-playing games",
    "Shogi",
    "Slot car racing",
    "Speedcubing",
    "Sport stacking",
    "Table football",
    "Table tennis",
    "Volleyball",
    "Weightlifting",
    "Wrestling",
    "Airsoft",
    "Archery",
    "Association football",
    "Australian rules football",
    "Auto racing",
    "Baseball",
    "Beach volleyball",
    "Breakdancing",
    "Climbing",
    "Cricket",
    "Croquet",
    "Cycling",
    "Disc golf",
    "Dog sport",
    "Equestrianism",
    "Exhibition drill",
    "Field hockey",
    "Figure skating",
    "Fishing",
    "Footbag",
    "Frisbee",
    "Golfing",
    "Handball",
    "Horseback riding",
    "Horseshoes",
    "Iceboat racing",
    "Jukskei",
    "Kart racing",
    "Knife throwing",
    "Lacrosse",
    "Longboarding",
    "Long-distance running",
    "Marching band",
    "Model aircraft",
    "Orienteering",
    "Pickleball",
    "Quidditch",
    "Race walking",
    "Racquetball",
    "Radio-controlled car racing",
    "Roller derby",
    "Rugby league football",
    "Sculling",
    "Shooting sport",
    "Skateboarding",
    "Skiing",
    "Sled dog racing",
    "Softball",
    "Speed skating",
    "Squash",
    "Surfing",
    "Swimming",
    "Table tennis",
    "Tennis",
    "Tennis polo",
    "Tether car",
    "Tour skating",
    "Tourism",
    "Trapshooting",
    "Triathlon",
    "Ultimate frisbee",
    "Volleyball",
    "Water polo",
    "Fishkeeping",
    "Learning",
    "Meditation",
    "Microscopy",
    "Reading",
    "Research",
    "Shortwave listening",
    "Audiophile",
    "Aircraft spotting",
    "Amateur astronomy",
    "Birdwatching",
    "Bus spotting",
    "Geocaching",
    "Gongoozling",
    "Herping",
    "Hiking",
    "Meteorology",
    "Photography",
    "Satellite watching",
    "Trainspotting",
    "Whale watching"
];

var randomPerson = function () {
    var f = FNkeys[Math.floor(FNkeys.length * Math.random())];
    var l = LNkeys[Math.floor(LNkeys.length * Math.random())];
    var cod = cods[Math.floor(cods.length * Math.random())];
    var hobby = hobbies[Math.floor(hobbies.length * Math.random())];
    return {
        name: `${f} ${l}`,
        country: countries[lastNames[l]],
        gender: firstNames[f],
        cod: cod,
        hobby: hobby,
        age: getAge()
    }
}

var verbs_hobby = [
    "really enjoyed",
    "just started",
    "hated",
    "passionately loved",
    "had an interest in",
    "recently tried",
    "studied",
    "won a prize in",
    "disliked",
    "came from a family specialized in",
    "specialized in",
    "always wanted to try",
    "did not get a chance to try",
    "looked forward to trying",
];

var verbs_family = [
    "loved",
    "hated",
    "fought a lot with",
    "always played with",
    "enjoyed walks with",
    "will be missed by",
    "lived with",
    "often watched tv with",
    "talked a lot with",
    "spent most of the time with",
]

var family = [
    "brother",
    "sister",
    "mother",
    "family",
    "cousin",
    "cat",
    "dog",
    "siblings",
    "best friend",
]



var trivia = function (r) {
    var p = "They";
    var pp = "their";
    if (r.gender == "M") { p = "He" } else if (r.gender == "F") { p = "She" };
    if (r.gender == "M") { pp = "his" } else if (r.gender == "F") { pp = "her" };
    var possibilities = [
        function () {
            var verb = verbs_hobby[Math.floor(verbs_hobby.length * Math.random())];
            return `${p} ${verb} ${r.hobby.toLowerCase()}`;
        },
        function () {
            var verb = verbs_hobby[Math.floor(verbs_hobby.length * Math.random())];
            return `${p} ${verb} ${r.hobby.toLowerCase()}`;
        },
        function () {
            var verb = verbs_family[Math.floor(verbs_family.length * Math.random())];
            var f = family[Math.floor(family.length * Math.random())];
            return `${p} ${verb} ${pp} ${f}`;
        }
    ];
    return possibilities[Math.floor(Math.random() * possibilities.length)]();
}

// Can display 1k blurb
var randomBlurb = function () {
    var r = randomPerson();
    return `${r.name} (aged ${r.age}) from ${r.country} ${r.cod}. ${trivia(r)}.
    `;
}

// Can display 100k names
var randomName = function () {
    var r = randomPerson();
    return `${r.name} (aged ${r.age}).`;
}

